# -*- coding: utf-8 -*-
"""Стартовое наполнение «Карты событий».

Каждое событие — одна редакционная карточка. Этот файл собирает JSON-документы
для коллекции `events` базы артефакта; страница данных в себе не держит.

Правила полей:
  dateStatus  confirmed | preliminary | expected | cancelled
  start/end   ISO-время с часовым поясом (+03:00 — Москва)
  window      для expected: крайняя дата окна «ожидается к ...»
  basis       agenda — подтверждено повесткой/документом; analysis — предположение редакции
"""
import json, os, sys

CHECKED = "2026-09-28"

A, N = "agenda", "analysis"


def ev(**k):
    k.setdefault("checkedAt", CHECKED)
    k.setdefault("phase", "upcoming")
    k.setdefault("allDay", False)
    return k


EVENTS = [
    # ------------------------------------------------------------------ 72 часа
    ev(
        id="eu-fac-2026-09-28",
        title="Совет ЕС по иностранным делам",
        kind="Заседание", cats=["intl", "russia"],
        where="Брюссель", start="2026-09-28T10:00:00+03:00", end="2026-09-28T19:00:00+03:00",
        timeNote="Начало заседания в 09:00 по Брюсселю (10:00 мск); время итоговой пресс-конференции не объявлено",
        dateStatus="confirmed", dateSource={"name": "EU Agenda / Совет ЕС", "url": "https://www.eubusiness.com/politics/eucalendar/"},
        participants="Министры иностранных дел стран ЕС, председательствует Верховный представитель ЕС",
        agenda=[
            {"text": "Военная поддержка Украины со стороны ЕС", "basis": A},
            {"text": "Гибридные угрозы (раздел «текущие вопросы»)", "basis": A},
        ],
        scenarios=[
            {"text": "Политическое обсуждение без юридически обязывающих решений: министры в этом формате чаще задают рамку, чем принимают акты", "basis": N},
            {"text": "Сигнал о подготовке 22-го пакета санкций. 21-й пакет принят 23 июля 2026 г.; о начале работы над следующим официально не объявлено", "basis": N},
        ],
        impact={
            "russia": "Главное — риторика о 22-м пакете и о финансировании военной помощи. Оно задаёт тон к саммиту ЕС 15–16 октября",
            "business": "Прямых последствий в день заседания нет. Экспортёрам стоит следить за формулировками о «теневом флоте» и третьих странах",
            "markets": "Ожидается слабая реакция рынков. Заметная реакция возможна только при неожиданном объявлении по санкциям",
        },
        checkpoint={"what": "Итоговое заявление Верховного представителя; следующий этап — Европейский совет", "when": "28 сентября, вечер; 15–16 октября", "date": "2026-10-15"},
        sources=[{"name": "EU Agenda, неделя 28 сентября — 3 октября", "url": "https://www.eubusiness.com/politics/eucalendar/"},
                 {"name": "Совет ЕС: хронология санкций", "url": "https://www.consilium.europa.eu/en/policies/sanctions-against-russia/timeline-sanctions-against-russia/"}],
    ),
    ev(
        id="valdai-2026",
        title="Ежегодное заседание клуба «Валдай»",
        kind="Форум", cats=["russia"],
        where="Московская область (перенесено из Сочи)", start="2026-09-28T10:00:00+03:00", end="2026-10-01T20:00:00+03:00",
        timeNote="Пленарная сессия с участием президента ожидается 1 октября; время не объявлено",
        dateStatus="confirmed",
        dateNote="Даты заседания подтверждены. Участие Владимира Путина и день пленарной сессии — по данным СМИ «как ожидается», официального анонса Кремля на 28 сентября нет",
        dateSource={"name": "РИА Новости, 28.09.2026", "url": "https://ria.ru/20260928/valday-2120598574.html"},
        participants="Около 120 участников, 74 из них — из-за рубежа; ожидается Владимир Путин",
        agenda=[
            {"text": "Тема: «Ответственность за будущее: пределы возможного или возможности без предела?»", "basis": A},
            {"text": "Доклад клуба: «политика сильных лидеров», ослабление институтов, рост роли государства", "basis": A},
        ],
        scenarios=[
            {"text": "Внешнеполитические заявления президента на пленарной сессии: Украина, отношения с США, БРИКС", "basis": N},
            {"text": "Оценки экономики на фоне бюджета-2027 с повышением налогов", "basis": N},
        ],
        impact={
            "russia": "Главная внешнеполитическая площадка осени. Цитаты с пленарной сессии задают повестку на неделю",
            "business": "Косвенно: сигналы о налогах, санкционной адаптации, параллельном импорте",
            "markets": "Реакция возможна при заявлениях о переговорах по Украине или об отношениях с США",
        },
        checkpoint={"what": "Стенограмма пленарной сессии на kremlin.ru", "when": "1 октября, вечер", "date": "2026-10-01"},
        sources=[{"name": "Коммерсантъ", "url": "https://www.kommersant.ru/doc/8988220"},
                 {"name": "РИА Новости", "url": "https://ria.ru/20260928/valday-2120598574.html"}],
    ),
    ev(
        id="ep-lagarde-2026-09-28",
        title="Денежный диалог Европарламента с Кристин Лагард",
        kind="Заседание", cats=["cb", "intl"],
        where="Брюссель, комитет ECON", start="2026-09-28T16:00:00+03:00",
        timeNote="Время начала — по программе комитета; уточнить в день события",
        dateStatus="confirmed", dateSource={"name": "EU Agenda", "url": "https://www.eubusiness.com/politics/eucalendar/"},
        participants="Кристин Лагард, депутаты комитета по экономике и денежной политике",
        agenda=[{"text": "Инфляция и влияние ИИ на экономику еврозоны", "basis": A}],
        scenarios=[
            {"text": "Сигнал о траектории ставки перед заседанием 29 октября: ЕЦБ уже дважды повышал ставку в 2026 году, депозитная сейчас 2,50%", "basis": N},
        ],
        impact={
            "russia": "Косвенно, через курс евро/доллар и стоимость расчётов в евро",
            "business": "Повышение ставок ЕЦБ удорожает финансирование в евро для контрагентов",
            "markets": "Евро и доходности европейских облигаций реагируют на любые слова о повышении ставки в октябре",
        },
        checkpoint={"what": "Заседание ЕЦБ по ставкам", "when": "29 октября", "date": "2026-10-29"},
        sources=[{"name": "EU Agenda", "url": "https://www.eubusiness.com/politics/eucalendar/"}],
    ),
    ev(
        id="duma-first-session-2026",
        title="Первое заседание Госдумы IX созыва",
        kind="Заседание", cats=["russia"],
        where="Москва, Государственная дума", start="2026-09-30T10:00:00+03:00",
        timeNote="Начало в 10:00 — по указу президента",
        dateStatus="confirmed", dateSource={"name": "Указ президента; РАПСИ, 25.09.2026", "url": "https://www.rapsinews.ru/legislation_news/20260925/312228888.html"},
        participants="450 депутатов: «Единая Россия» — 349 мандатов, остальные партии — 101",
        agenda=[
            {"text": "Избрание председателя Госдумы и его заместителей", "basis": A},
            {"text": "Формирование комитетов", "basis": A},
        ],
        scenarios=[
            {"text": "Переизбрание Вячеслава Володина председателем", "basis": N},
            {"text": "У «Единой России» конституционное большинство в одиночку (349 из 450 при пороге 300), поэтому распределение комитетов определяет она", "basis": N},
        ],
        impact={
            "russia": "Новая Дума сразу получает бюджет-2027 и налоговый пакет. Её состав фактически гарантирует их принятие",
            "business": "Главный вопрос — кто возглавит комитет по бюджету и налогам: от него зависит судьба поправок в НК",
            "markets": "Ожидается слабая реакция рынков",
        },
        checkpoint={"what": "Состав руководства и комитетов; назначение первого чтения бюджета", "when": "30 сентября — начало октября", "date": "2026-10-02"},
        sources=[{"name": "РАПСИ", "url": "https://www.rapsinews.ru/legislation_news/20260925/312228888.html"},
                 {"name": "Ведомости: распределение мандатов", "url": "https://www.vedomosti.ru/politics/news/2026/09/25/1231790-mandatov-v-gosdume"}],
    ),
    ev(
        id="rosstat-cpi-weekly-2026-09-30",
        title="Недельная инфляция Росстата",
        kind="Публикация данных", cats=["stats", "russia"],
        where="Росстат", start="2026-09-30T19:00:00+03:00",
        timeNote="Регулярная публикация по средам в 19:00",
        dateStatus="confirmed", dateSource={"name": "Росстат, регулярный график", "url": "https://rosstat.gov.ru/statistics/price"},
        participants="—",
        agenda=[{"text": "Оценка ИПЦ за неделю с 23 по 29 сентября", "basis": A}],
        scenarios=[
            {"text": "Сохранение повышенного недельного темпа. В сентябре Банк России оценил устойчивый рост цен в 5–6% в пересчёте на год", "basis": N},
        ],
        impact={
            "russia": "Последние недельные данные сентября перед опорным заседанием ЦБ 23 октября",
            "business": "Влияет на ожидания по ставкам кредитов и депозитов",
            "markets": "ОФЗ и ставки денежного рынка реагируют на отклонения от ожиданий",
        },
        checkpoint={"what": "Месячный ИПЦ за сентябрь", "when": "ориентировочно середина октября", "date": "2026-10-14"},
        sources=[{"name": "Росстат: цены и инфляция", "url": "https://rosstat.gov.ru/statistics/price"}],
    ),
    ev(
        id="budget-2027-submission",
        title="Внесение проекта бюджета на 2027–2029 годы в Госдуму",
        kind="Публикация документа", cats=["russia", "business"],
        where="Правительство → Госдума", start="2026-10-01T00:00:00+03:00", allDay=True,
        dateWording="не позднее 1 октября",
        timeNote="Крайний срок по Бюджетному кодексу; день и час внесения не объявлены",
        dateStatus="confirmed", dateNote="Подтверждён крайний срок, а не день внесения: документ может поступить раньше",
        dateSource={"name": "Интерфакс", "url": "https://www.interfax.ru/business/1118285"},
        participants="Минфин, правительство, новая Госдума",
        agenda=[
            {"text": "Доходы 2027 — 43,3 трлн руб., расходы — 48,8 трлн руб., дефицит — 2,2% ВВП (ожидаемый дефицит 2026 г. — 3%)", "basis": A},
            {"text": "Пакет поправок в Налоговый кодекс «для повышения устойчивости бюджетной системы» (внесён Минфином в правительство 24 сентября)", "basis": A},
            {"text": "Приоритеты: семьи с детьми, оборона и безопасность, участники СВО, технологическое лидерство", "basis": A},
        ],
        scenarios=[
            {"text": "Параметры не изменятся между одобрением правительством и внесением", "basis": N},
            {"text": "Основная борьба развернётся вокруг налогового пакета, а не расходов", "basis": N},
        ],
        impact={
            "russia": "Консолидация: дефицит снижается с 3% до 2,2% ВВП за счёт роста налогов и сокращения трат",
            "business": "Налоговый пакет — главный риск для маржи. Важны ставки, льготы, сроки вступления в силу",
            "markets": "Предложение ОФЗ зависит от дефицита; более низкий дефицит поддерживает облигации",
        },
        checkpoint={"what": "Назначение первого чтения Советом Думы", "when": "октябрь; дата не назначена", "date": "2026-10-20"},
        sources=[{"name": "Ведомости: правительство одобрило проект", "url": "https://www.vedomosti.ru/economics/news/2026/09/24/1231650-pravitelstvo-odobrilo-proekt-byudzheta"},
                 {"name": "Ведомости: главное из проекта", "url": "https://www.vedomosti.ru/economics/articles/2026/09/24/1231407-minfin-vnes"}],
    ),
    # ------------------------------------------------------------------ две недели
    ev(
        id="us-nfp-2026-10-02",
        title="США: занятость вне сельского хозяйства за сентябрь",
        kind="Публикация данных", cats=["stats", "cb"],
        where="Бюро статистики труда США (BLS)", start="2026-10-02T15:30:00+03:00",
        timeNote="08:30 по Вашингтону = 15:30 мск",
        dateStatus="confirmed", dateSource={"name": "BLS: график релизов", "url": "https://www.bls.gov/schedule/news_release/empsit.htm"},
        participants="—",
        agenda=[{"text": "Число рабочих мест, безработица, зарплаты за сентябрь", "basis": A}],
        scenarios=[
            {"text": "Сильный отчёт укрепит ожидания второго повышения ставки ФРС в 2026 г. (рынки закладывали одно повышение на 25 б.п. до конца года)", "basis": N},
        ],
        impact={
            "russia": "Через доллар и нефть: жёсткая ФРС укрепляет доллар и давит на сырьё",
            "business": "Экспортёрам важна долларовая цена сырья",
            "markets": "Один из главных релизов месяца для доллара и Treasuries",
        },
        checkpoint={"what": "Индекс потребительских цен США", "when": "14 октября, 15:30 мск", "date": "2026-10-14"},
        sources=[{"name": "BLS", "url": "https://www.bls.gov/schedule/news_release/empsit.htm"}],
    ),
    ev(
        id="latvia-saeima-2026",
        title="Выборы в Сейм Латвии",
        kind="Выборы", cats=["elections", "intl"],
        where="Латвия", start="2026-10-03T08:00:00+03:00", end="2026-10-03T20:00:00+03:00",
        timeNote="Участки открыты с 8:00 до 20:00 (время в Латвии совпадает с московским)",
        dateStatus="confirmed", ideaWording="Expected by October 2026",
        ideaCheck="IDEA пишет «ожидаются к октябрю», но дата уже определена законом: первая суббота октября, 3 октября",
        dateSource={"name": "LSM", "url": "https://eng.lsm.lv/article/politics/election/02.09.2026-latvian-saeima-elections-2026-how-the-election-works.a658525/"},
        participants="14 партий и объединений, барьер 5%, 100 мест",
        agenda=[{"text": "Избрание 15-го Сейма на четыре года", "basis": A}],
        scenarios=[
            {"text": "Коалиционное правительство при сохранении прежнего курса по России и Украине", "basis": N},
        ],
        impact={
            "russia": "Отношение к русскоязычному меньшинству и к транзиту; радикальной смены курса ожидать не стоит",
            "business": "Транзит через Латвию для российских грузов практически закрыт",
            "markets": "Реакции рынков не ожидается",
        },
        checkpoint={"what": "Официальные итоги ЦИК Латвии; переговоры о коалиции", "when": "4–10 октября", "date": "2026-10-10"},
        sources=[{"name": "LSM: как устроены выборы", "url": "https://eng.lsm.lv/article/politics/election/02.09.2026-latvian-saeima-elections-2026-how-the-election-works.a658525/"}],
    ),
    ev(
        id="brazil-general-2026",
        title="Всеобщие выборы в Бразилии, первый тур",
        kind="Выборы", cats=["elections", "intl"],
        where="Бразилия", start="2026-10-04T14:00:00+03:00", end="2026-10-04T23:00:00+03:00",
        timeNote="Участки закрываются в 17:00 по Бразилиа = 23:00 мск; предварительные итоги ночью",
        dateStatus="confirmed", ideaWording="scheduled to be held on 4 October 2026",
        dateSource={"name": "Конституционный график: первое воскресенье октября", "url": "https://en.wikipedia.org/wiki/2026_Brazilian_general_election"},
        participants="Президент, Конгресс, губернаторы, законодательные собрания штатов",
        agenda=[{"text": "Выборы президента и вице-президента, Конгресса, губернаторов", "basis": A}],
        scenarios=[
            {"text": "Если никто не наберёт больше 50%, второй тур пройдёт 25 октября", "basis": A},
            {"text": "Смена или сохранение курса в БРИКС зависит от победителя", "basis": N},
        ],
        impact={
            "russia": "Бразилия — партнёр по БРИКС и крупный покупатель российских удобрений и дизеля",
            "business": "Экспорт удобрений и нефтепродуктов в Бразилию",
            "markets": "Бразильский реал и сырьевые рынки",
        },
        checkpoint={"what": "Второй тур (если потребуется)", "when": "25 октября", "date": "2026-10-25"},
        sources=[{"name": "Выборы в Бразилии 2026", "url": "https://en.wikipedia.org/wiki/2026_Brazilian_general_election"}],
    ),
    ev(
        id="bih-general-2026",
        title="Всеобщие выборы в Боснии и Герцеговине",
        kind="Выборы", cats=["elections", "intl"],
        where="Босния и Герцеговина", start="2026-10-04T08:00:00+03:00", end="2026-10-04T20:00:00+03:00",
        timeNote="Участки с 7:00 до 19:00 по местному = 8:00–20:00 мск",
        dateStatus="confirmed", ideaWording="Expected by October 2026",
        ideaCheck="IDEA пишет «ожидаются к октябрю», но ЦИК БиГ ещё 7 мая назначил выборы на 4 октября",
        dateSource={"name": "European Western Balkans", "url": "http://europeanwesternbalkans.com/2026/05/07/the-general-election-in-bih-to-be-held-on-4-october/"},
        participants="3,4 млн избирателей; президиум БиГ, парламенты, президент Республики Сербской",
        agenda=[{"text": "Президиум БиГ, парламенты всех уровней, президент и вице-президенты Республики Сербской", "basis": A}],
        scenarios=[
            {"text": "Выборы президента Республики Сербской определят, сохранится ли её сближение с Москвой", "basis": N},
        ],
        impact={
            "russia": "Республика Сербская — ближайший партнёр России на Балканах",
            "business": "Прямых последствий для бизнеса не ожидается",
            "markets": "Реакции рынков не ожидается",
        },
        checkpoint={"what": "Предварительные итоги ЦИК БиГ", "when": "5 октября", "date": "2026-10-05"},
        sources=[{"name": "Balkan Insight", "url": "https://balkaninsight.com/2026/05/07/bosnia-sets-october-election-date-amid-push-for-new-voting-technology/bi/"}],
    ),
    ev(
        id="opec-plus-2026-10-04",
        title="Встреча стран ОПЕК+ с добровольными ограничениями",
        kind="Заседание", cats=["intl", "russia", "business"],
        where="Онлайн", start="2026-10-04T00:00:00+03:00", allDay=True,
        timeNote="Дата подтверждена ОПЕК, время не объявлено",
        dateStatus="confirmed", dateSource={"name": "ОПЕК, пресс-релиз 6 сентября 2026", "url": "https://www.opec.org/pr-detail/613-6-september-2026.html"},
        participants="Саудовская Аравия, Россия, Ирак, Кувейт, Казахстан, Алжир, Оман (семь стран)",
        agenda=[{"text": "Уровень добычи на ноябрь 2026 г.", "basis": A}],
        scenarios=[
            {"text": "Сохранить уровень сентября ещё на месяц. Так решили 6 сентября для октября", "basis": N},
            {"text": "Увеличить добычу при высоких ценах на фоне ближневосточного конфликта", "basis": N},
        ],
        impact={
            "russia": "Квота напрямую влияет на нефтегазовые доходы бюджета-2027",
            "business": "Нефтяные компании: объёмы добычи и экспорта",
            "markets": "Brent, рубль",
        },
        checkpoint={"what": "Следующая встреча — ориентировочно первое воскресенье ноября", "when": "дата будет в итоговом релизе", "date": "2026-11-01"},
        sources=[{"name": "ОПЕК", "url": "https://www.opec.org/pr-detail/613-6-september-2026.html"}],
    ),
    ev(
        id="cis-summit-2026",
        title="Саммит СНГ",
        kind="Саммит", cats=["russia", "intl"],
        where="Туркменбаши, «Аваза» (Туркмения)", start="2026-10-09T00:00:00+03:00", allDay=True,
        timeNote="Совет министров иностранных дел — 7 октября, там же",
        dateStatus="confirmed", dateSource={"name": "ТАСС", "url": "https://tass.ru/mezhdunarodnaya-panorama/26059751"},
        participants="Главы государств СНГ; ожидается Владимир Путин",
        agenda=[{"text": "Заседание Совета глав государств СНГ; перед ним — СМИД 7 октября", "basis": A}],
        scenarios=[
            {"text": "Пакет документов по экономическому и гуманитарному сотрудничеству", "basis": N},
            {"text": "Двусторонние встречи Путина с лидерами Центральной Азии и Азербайджана", "basis": N},
        ],
        impact={
            "russia": "Сигналы о состоянии отношений с Азербайджаном и Центральной Азией",
            "business": "Логистические коридоры через Каспий, трудовая миграция",
            "markets": "Реакции рынков не ожидается",
        },
        checkpoint={"what": "Перечень подписанных документов", "when": "9 октября, вечер", "date": "2026-10-09"},
        sources=[{"name": "ТАСС", "url": "https://tass.ru/mezhdunarodnaya-panorama/26059751"},
                 {"name": "Sputnik Беларусь", "url": "https://sputnik.by/20260728/sammity-glav-gosudarstv-i-midov-sng-proydut-v-oktyabre-1109461866.html"}],
    ),
    ev(
        id="imf-wb-annual-2026",
        title="Ежегодные собрания МВФ и Всемирного банка",
        kind="Форум", cats=["intl", "stats"],
        where="Бангкок, Таиланд", start="2026-10-12T04:00:00+03:00", end="2026-10-18T18:00:00+03:00",
        timeNote="Пленарная сессия — 16 октября",
        dateStatus="confirmed", dateSource={"name": "МВФ", "url": "https://www.imf.org/en/meetings/2026/annual"},
        participants="Министры финансов и главы центробанков стран — членов МВФ",
        agenda=[
            {"text": "Пленарное заседание 16 октября", "basis": A},
            {"text": "Публикация «Перспектив мировой экономики» (WEO) и доклада о финансовой стабильности (GFSR) — традиционно в первые дни собраний", "basis": N},
        ],
        scenarios=[
            {"text": "Понижение прогноза мирового роста из-за ближневосточного конфликта и цен на энергоносители", "basis": N},
            {"text": "Новый прогноз МВФ по России", "basis": N},
        ],
        impact={
            "russia": "Прогноз МВФ по ВВП и инфляции России",
            "business": "Внешний фон: спрос и цены на сырьё",
            "markets": "Оценки финансовой стабильности, долговых рисков и ИИ-пузыря",
        },
        checkpoint={"what": "Коммюнике Международного валютно-финансового комитета (IMFC)", "when": "около 17 октября", "date": "2026-10-17"},
        sources=[{"name": "МВФ: Annual Meetings 2026", "url": "https://www.imf.org/en/meetings/2026/annual/schedule"}],
    ),
    ev(
        id="jpm-q3-2026",
        title="JPMorgan Chase: отчётность за III квартал",
        kind="Отчётность", cats=["business"],
        where="Нью-Йорк", start="2026-10-13T14:00:00+03:00",
        timeNote="Релиз около 07:00 по Нью-Йорку (14:00 мск), звонок в 15:30 мск",
        dateStatus="confirmed", dateSource={"name": "JPMorganChase IR", "url": "https://www.jpmorganchase.com/ir/news/2026/jpmc-to-host-third-quarter-2026-earnings-call"},
        participants="Руководство банка",
        agenda=[{"text": "Результаты III квартала 2026 г.", "basis": A}],
        scenarios=[{"text": "Открывает сезон отчётности американских банков; внимание к кредитному качеству при растущих ставках", "basis": N}],
        impact={"russia": "Прямых последствий нет", "business": "Индикатор кредитного цикла США", "markets": "Задаёт тон сезону отчётности"},
        checkpoint={"what": "Отчёты остальных крупных банков США", "when": "13–16 октября", "date": "2026-10-16"},
        sources=[{"name": "JPMorganChase IR", "url": "https://www.jpmorganchase.com/ir/news/2026/jpmc-to-host-third-quarter-2026-earnings-call"}],
    ),
    ev(
        id="rosstat-cpi-sep-2026",
        title="Росстат: инфляция за сентябрь",
        kind="Публикация данных", cats=["stats", "russia"],
        where="Росстат", start="2026-10-14T19:00:00+03:00",
        timeNote="Точная дата — по графику срочных публикаций Росстата; при сверке график был недоступен",
        dateStatus="preliminary", dateNote="Дата ориентировочная, по практике прошлых лет. Сверить с графиком Росстата",
        dateSource={"name": "Росстат: график срочных публикаций", "url": "https://rosstat.gov.ru/compendium/document/50798"},
        participants="—",
        agenda=[{"text": "ИПЦ за сентябрь, годовой темп", "basis": A}],
        scenarios=[{"text": "Годовая инфляция внутри прогноза ЦБ на конец года (6–7%) или выше него", "basis": N}],
        impact={"russia": "Ключевые данные перед заседанием ЦБ 23 октября", "business": "Индексация цен и зарплат", "markets": "ОФЗ, ожидания по ставке"},
        checkpoint={"what": "Заседание Банка России", "when": "23 октября", "date": "2026-10-23"},
        sources=[{"name": "Росстат", "url": "https://rosstat.gov.ru/statistics/price"}],
    ),
    ev(
        id="us-cpi-2026-10-14",
        title="США: индекс потребительских цен за сентябрь",
        kind="Публикация данных", cats=["stats", "cb"],
        where="BLS", start="2026-10-14T15:30:00+03:00",
        timeNote="08:30 по Вашингтону = 15:30 мск",
        dateStatus="confirmed", dateSource={"name": "BLS", "url": "https://www.bls.gov/schedule/2026/10_sched_list.htm"},
        participants="—", agenda=[{"text": "ИПЦ и базовый ИПЦ за сентябрь", "basis": A}],
        scenarios=[{"text": "Инфляция выше цели заставит ФРС снова повысить ставку 28 октября", "basis": N}],
        impact={"russia": "Через доллар и нефть", "business": "—", "markets": "Главный вход для решения ФРС 28 октября"},
        checkpoint={"what": "Заседание ФРС", "when": "27–28 октября", "date": "2026-10-28"},
        sources=[{"name": "BLS", "url": "https://www.bls.gov/schedule/2026/10_sched_list.htm"}],
    ),
    ev(
        id="ren-2026",
        title="Российская энергетическая неделя",
        kind="Форум", cats=["russia", "business"],
        where="Москва, Манеж и Гостиный двор", start="2026-10-14T10:00:00+03:00", end="2026-10-16T19:00:00+03:00",
        timeNote="Молодёжный день — 16 октября; программа пленарного заседания не опубликована",
        dateStatus="confirmed", dateSource={"name": "Росконгресс / Минэнерго", "url": "https://energy.s-kon.ru/utverzhdeny-daty-provedeniya-mezhdunarodnogo-foruma-rossijskaya-energeticheskaya-nedelya-2026/"},
        participants="Минэнерго, нефтегазовые и энергетические компании; участие президента не объявлено",
        agenda=[{"text": "Стратегическая дискуссионная программа, инженерная программа, выставка ТЭК", "basis": A}],
        scenarios=[
            {"text": "Выступление президента на пленарной сессии, как в прошлые годы; в 2026 г. пока не анонсировано", "basis": N},
            {"text": "Заявления о ценовой политике ОПЕК+ и экспорте в Азию", "basis": N},
        ],
        impact={"russia": "Позиция по нефтяному рынку и налогам ТЭК", "business": "Нефтегаз, электроэнергетика, соглашения на полях", "markets": "Нефтегазовые акции"},
        checkpoint={"what": "Итоговые соглашения и заявления", "when": "16 октября", "date": "2026-10-16"},
        sources=[{"name": "РЭН", "url": "https://rusenergyweek.com/"}],
    ),
    ev(
        id="euco-2026-10",
        title="Европейский совет",
        kind="Саммит", cats=["intl", "russia"],
        where="Брюссель", start="2026-10-15T11:00:00+03:00", end="2026-10-16T19:00:00+03:00",
        timeNote="Время начала — по программе председателя Европейского совета",
        dateStatus="confirmed", dateSource={"name": "Совет ЕС", "url": "https://www.consilium.europa.eu/en/meetings/european-council/2026/10/15-16/"},
        participants="Главы государств и правительств ЕС",
        agenda=[{"text": "Повестка будет опубликована в аннотированной программе, обычно за 3–4 недели", "basis": A}],
        scenarios=[
            {"text": "Украина, оборона, санкции, конкурентоспособность и миграция — обычный осенний набор тем", "basis": N},
            {"text": "Политическое одобрение параметров 22-го пакета санкций", "basis": N},
        ],
        impact={"russia": "Санкции и использование замороженных активов", "business": "Экспортные ограничения", "markets": "Евро, европейский оборонный сектор"},
        checkpoint={"what": "Итоговые выводы (conclusions)", "when": "16 октября", "date": "2026-10-16"},
        sources=[{"name": "Совет ЕС", "url": "https://www.consilium.europa.eu/en/meetings/european-council/2026/10/15-16/"}],
    ),
    # ------------------------------------------------------------------ три месяца
    ev(
        id="duma-budget-first-reading-2026",
        title="Госдума: первое чтение бюджета на 2027–2029 годы",
        kind="Заседание", cats=["russia", "business"],
        where="Москва, Государственная дума", start=None, window="2026-10-31",
        dateWording="в октябре, дата не назначена",
        timeNote="В 2025 г. первое чтение прошло 22 октября; дату этого года назначит Совет Думы",
        dateStatus="expected", dateSource={"name": "Практика прошлых лет: Госдума, 2025", "url": "http://duma.gov.ru/news/62311/"},
        participants="Госдума IX созыва, Минфин",
        agenda=[{"text": "Основные характеристики бюджета: доходы, расходы, дефицит", "basis": A}],
        scenarios=[{"text": "Принятие в первом чтении без изменения основных характеристик при конституционном большинстве «Единой России»", "basis": N}],
        impact={"russia": "Фиксирует дефицит и налоговую нагрузку на 2027 г.", "business": "Поправки в НК обычно идут вместе с бюджетом", "markets": "ОФЗ"},
        checkpoint={"what": "Второе чтение (распределение расходов)", "when": "ноябрь", "date": "2026-11-20"},
        sources=[{"name": "Госдума", "url": "http://duma.gov.ru/news/62311/"}],
    ),
    ev(
        id="cbr-2026-10-23",
        title="Банк России: решение по ключевой ставке (опорное заседание)",
        kind="Заседание", cats=["cb", "russia"],
        where="Москва", start="2026-10-23T13:30:00+03:00",
        timeNote="Решение в 13:30 мск, пресс-конференция в 15:00 мск",
        dateStatus="confirmed", dateSource={"name": "Банк России: календарь решений", "url": "https://cbr.ru/dkp/cal_mp/"},
        participants="Совет директоров Банка России; пресс-конференция председателя",
        agenda=[
            {"text": "Ключевая ставка, сейчас 14,00%", "basis": A},
            {"text": "Опорное заседание: публикуется обновлённый среднесрочный прогноз", "basis": A},
        ],
        scenarios=[
            {"text": "Сохранение 14%: 11 сентября ЦБ оставил ставку и прогноз инфляции 6–7% на конец года, отметив ускорение устойчивого роста цен до 5–6%", "basis": N},
            {"text": "Повышение ставки в случае ухудшения инфляционных данных за сентябрь–октябрь", "basis": N},
            {"text": "Снижение маловероятно при нынешней риторике", "basis": N},
        ],
        impact={"russia": "Главное решение осени для экономики", "business": "Стоимость кредита, инвестпрограммы", "markets": "ОФЗ, рубль, банковские акции"},
        checkpoint={"what": "Резюме обсуждения ключевой ставки; следующее заседание", "when": "4 ноября (обычно через 8 рабочих дней); 18 декабря", "date": "2026-12-18"},
        sources=[{"name": "Банк России", "url": "https://cbr.ru/dkp/cal_mp/"},
                 {"name": "Пресс-релиз 11 сентября", "url": "https://www.cbr.ru/press/keypr/"}],
    ),
    ev(
        id="bulgaria-president-2026",
        title="Президентские выборы в Болгарии",
        kind="Выборы", cats=["elections", "intl"],
        where="Болгария", start="2026-10-25T08:00:00+03:00", end="2026-10-25T21:00:00+03:00",
        timeNote="Участки с 7:00 до 20:00 по местному (с 25 октября — зимнее время, UTC+2) = 8:00–21:00 мск",
        dateStatus="confirmed", ideaWording="Expected by November 2026",
        ideaCheck="IDEA пишет «ожидаются к ноябрю», но парламент 31 июля утвердил дату 25 октября; второй тур, если понадобится, — 1 ноября",
        dateSource={"name": "The Sofia Globe", "url": "https://sofiaglobe.com/2026/07/31/bulgarian-mps-approve-october-25-date-for-presidential-elections/"},
        participants="Кандидаты в президенты; официальная кампания с 25 сентября",
        agenda=[{"text": "Выборы президента; второй тур 1 ноября, если никто не наберёт 50%", "basis": A}],
        scenarios=[{"text": "Вопрос отношения к России и к поставкам Украине в центре кампании на фоне политического кризиса 2021–2026 гг.", "basis": N}],
        impact={"russia": "Болгария — транзит газа по «Турецкому потоку»", "business": "Транзит газа в Сербию и Венгрию", "markets": "Реакции рынков не ожидается"},
        checkpoint={"what": "Второй тур", "when": "1 ноября", "date": "2026-11-01"},
        sources=[{"name": "The Sofia Globe: справка", "url": "https://sofiaglobe.com/2026/09/25/bulgarias-2026-presidential-elections-the-sofia-globes-factfile/"}],
    ),
    ev(
        id="brazil-runoff-2026",
        title="Бразилия: второй тур президентских выборов",
        kind="Выборы", cats=["elections", "intl"],
        where="Бразилия", start="2026-10-25T14:00:00+03:00", end="2026-10-25T23:00:00+03:00",
        dateStatus="preliminary", dateNote="Дата установлена законом, но сам второй тур состоится, только если в первом туре 4 октября никто не наберёт больше 50%",
        dateSource={"name": "Выборы в Бразилии 2026", "url": "https://en.wikipedia.org/wiki/2026_Brazilian_general_election"},
        participants="Два лидера первого тура",
        agenda=[{"text": "Второй тур, если он понадобится", "basis": A}],
        scenarios=[], impact={"russia": "См. первый тур", "business": "—", "markets": "Бразильский реал"},
        checkpoint={"what": "Итоги первого тура покажут, нужен ли второй", "when": "5 октября", "date": "2026-10-05"},
        sources=[{"name": "Выборы в Бразилии 2026", "url": "https://en.wikipedia.org/wiki/2026_Brazilian_general_election"}],
    ),
    ev(
        id="israel-knesset-2026",
        title="Выборы в Кнессет Израиля",
        kind="Выборы", cats=["elections", "intl"],
        where="Израиль", start="2026-10-27T08:00:00+03:00", end="2026-10-27T23:00:00+03:00",
        timeNote="Участки закрываются в 22:00 по местному = 23:00 мск; экзит-поллы сразу после закрытия",
        dateStatus="confirmed", ideaWording="scheduled for 27 October 2026",
        dateSource={"name": "Al Jazeera: Кнессет распущен", "url": "https://www.aljazeera.com/news/2026/7/17/knesset-dissolves-how-will-israel-vote-in-octobers-general-election"},
        participants="Израильские партии; первые выборы после войн 2023–2026 гг., включая войну с Ираном 2026 г.",
        agenda=[{"text": "Выборы 120 депутатов Кнессета", "basis": A}],
        scenarios=[{"text": "Долгие коалиционные переговоры; исход определит политику по Ирану и Газе", "basis": N}],
        impact={"russia": "Ближневосточный конфликт — главный фактор цен на нефть", "business": "—", "markets": "Нефть через премию за риск на Ближнем Востоке"},
        checkpoint={"what": "Окончательные итоги ЦИК; поручение сформировать правительство", "when": "начало ноября", "date": "2026-11-05"},
        sources=[{"name": "Britannica", "url": "https://www.britannica.com/event/2026-Israeli-Elections"}],
    ),
    ev(
        id="fomc-2026-10",
        title="ФРС: решение по ставке",
        kind="Заседание", cats=["cb", "intl"],
        where="Вашингтон", start="2026-10-28T21:00:00+03:00",
        timeNote="Заседание 27–28 октября. Решение в 14:00 по Вашингтону = 21:00 мск, пресс-конференция в 21:30 мск",
        dateStatus="confirmed", dateSource={"name": "ФРС: календарь FOMC", "url": "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm"},
        participants="Комитет по открытым рынкам (FOMC)",
        agenda=[{"text": "Целевой диапазон ставки, сейчас 3,75–4,00%", "basis": A}],
        scenarios=[
            {"text": "Ещё одно повышение на 25 б.п.: рынки закладывали одно повышение до конца 2026 г., прогнозы членов FOMC на конец года — 4,1–4,4%", "basis": N},
            {"text": "Пауза при слабых данных по рынку труда", "basis": N},
        ],
        impact={"russia": "Сильный доллар давит на нефть и валюты развивающихся стран", "business": "—", "markets": "Главное событие месяца для мировых рынков"},
        checkpoint={"what": "Протокол заседания; следующее заседание", "when": "через три недели; 8–9 декабря", "date": "2026-12-09"},
        sources=[{"name": "ФРС", "url": "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm"},
                 {"name": "CNBC: решение 16 сентября", "url": "https://www.cnbc.com/2026/09/16/fed-rate-decision-september-2026.html"}],
    ),
    ev(
        id="ecb-2026-10",
        title="ЕЦБ: решение по ставкам",
        kind="Заседание", cats=["cb", "intl"],
        where="Франкфурт", start="2026-10-29T16:15:00+03:00",
        timeNote="Решение в 14:15 по Франкфурту (с 25 октября — зимнее время) = 16:15 мск, пресс-конференция в 16:45 мск",
        dateStatus="confirmed", dateSource={"name": "ЕЦБ: календарь", "url": "https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html"},
        participants="Управляющий совет ЕЦБ",
        agenda=[{"text": "Ставки: депозитная — 2,50%, основная — 2,65%", "basis": A}, {"text": "Заседание без новых макропрогнозов", "basis": A}],
        scenarios=[{"text": "Пауза после двух повышений (июнь и сентябрь) или третье повышение из-за энергетической инфляции", "basis": N}],
        impact={"russia": "Курс евро", "business": "Стоимость финансирования в евро", "markets": "Евро, европейские облигации"},
        checkpoint={"what": "Следующее заседание с прогнозами", "when": "17 декабря", "date": "2026-12-17"},
        sources=[{"name": "ЕЦБ", "url": "https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html"}],
    ),
    ev(
        id="sber-ifrs-9m-2026",
        title="Сбербанк: МСФО за 9 месяцев",
        kind="Отчётность", cats=["business", "russia"],
        where="Москва", start=None, window="2026-10-31",
        dateWording="конец октября, дата не объявлена",
        timeNote="Отчёт за II квартал вышел 29 июля; дата публикации за 9 месяцев не объявлена",
        dateStatus="expected", dateSource={"name": "Сбер: раскрытие", "url": "https://www.sberbank.com/ru/investor-relations/groupresults"},
        participants="Руководство Сбера",
        agenda=[{"text": "Результаты за 9 месяцев 2026 г.", "basis": A}],
        scenarios=[{"text": "Давление на прибыль банков при ставке 14% и росте налогов", "basis": N}],
        impact={"russia": "Индикатор кредитной активности", "business": "Кредитование", "markets": "Акции Сбера — крупнейшая бумага индекса Мосбиржи"},
        checkpoint={"what": "Дата появится в календаре IR Сбера", "when": "октябрь", "date": "2026-10-31"},
        sources=[{"name": "Сбер IR", "url": "https://www.sberbank.com/ru/investor-relations/groupresults"}],
    ),
    ev(
        id="us-midterms-2026",
        title="Промежуточные выборы в США",
        kind="Выборы", cats=["elections", "intl"],
        where="США", start="2026-11-03T14:00:00+03:00", end="2026-11-04T07:00:00+03:00",
        timeNote="Первые участки закрываются в 19:00 по Восточному времени = 03:00 мск 4 ноября",
        dateStatus="confirmed", ideaWording="scheduled to be held on 3 November 2026",
        dateSource={"name": "Федеральный закон: вторник после первого понедельника ноября", "url": "https://www.idea.int/democracytracker/elections-list"},
        participants="Вся Палата представителей, треть Сената, губернаторы",
        agenda=[{"text": "Контроль над Конгрессом", "basis": A}],
        scenarios=[{"text": "Смена большинства хотя бы в одной палате ограничит повестку администрации Трампа", "basis": N}],
        impact={"russia": "Санкционная политика и помощь Украине зависят от Конгресса", "business": "—", "markets": "Доллар, американские акции"},
        checkpoint={"what": "Бюджетный срок 11 декабря — первое испытание для нового расклада сил", "when": "11 декабря", "date": "2026-12-11"},
        sources=[{"name": "IDEA", "url": "https://www.idea.int/democracytracker/elections-list"}],
    ),
    ev(
        id="nz-general-2026",
        title="Всеобщие выборы в Новой Зеландии",
        kind="Выборы", cats=["elections", "intl"],
        where="Новая Зеландия", start="2026-11-07T00:00:00+03:00", end="2026-11-07T09:00:00+03:00",
        timeNote="Участки закрываются в 19:00 по Веллингтону = 09:00 мск; досрочное голосование с 26 октября",
        dateStatus="confirmed", ideaWording="scheduled to be held on 7 November 2026",
        dateSource={"name": "Правительство НЗ", "url": "https://www.beehive.govt.nz/release/general-election-be-held-7-november"},
        participants="Партии Новой Зеландии",
        agenda=[{"text": "Выборы парламента", "basis": A}],
        scenarios=[], impact={"russia": "Прямых последствий нет", "business": "—", "markets": "Новозеландский доллар"},
        checkpoint={"what": "Официальные итоги", "when": "конец ноября", "date": "2026-11-27"},
        sources=[{"name": "Beehive.govt.nz", "url": "https://www.beehive.govt.nz/release/general-election-be-held-7-november"}],
    ),
    ev(
        id="cop31-2026",
        title="Климатическая конференция ООН COP31",
        kind="Саммит", cats=["intl"],
        where="Анталья, Турция", start="2026-11-09T10:00:00+03:00", end="2026-11-20T20:00:00+03:00",
        timeNote="Саммит мировых лидеров — 11–12 ноября",
        dateStatus="confirmed", dateSource={"name": "РКИК ООН", "url": "https://unfccc.int/cop31/ifp"},
        participants="Стороны Рамочной конвенции ООН об изменении климата",
        agenda=[{"text": "Переговоры по климатическому финансированию и национальным планам", "basis": A}],
        scenarios=[{"text": "Продление переговоров за пределы 20 ноября — это обычная практика", "basis": N}],
        impact={"russia": "Углеродное регулирование, пограничный углеродный механизм ЕС (CBAM)", "business": "Экспортёры в ЕС", "markets": "Слабая реакция рынков"},
        checkpoint={"what": "Итоговое решение конференции", "when": "20 ноября или позже", "date": "2026-11-20"},
        sources=[{"name": "РКИК ООН", "url": "https://unfccc.int/cop31/ifp"}],
    ),
    ev(
        id="bahrain-2026",
        title="Парламентские выборы в Бахрейне",
        kind="Выборы", cats=["elections", "intl"],
        where="Бахрейн", start=None, window="2026-11-30",
        dateWording="«к ноябрю 2026» по IDEA; под вопросом",
        dateStatus="expected", ideaWording="Expected to be held by November 2026",
        ideaCheck="По IDEA выборы «ожидаются к ноябрю», но, по данным справочных источников, в апреле 2026 г. полномочия действующей палаты продлили до декабря 2027 г. До официального решения называть ноябрь нельзя",
        dateSource={"name": "IFES Election Guide", "url": "https://www.electionguide.org/elections/id/5100/"},
        participants="—", agenda=[{"text": "Выборы Совета представителей", "basis": A}],
        scenarios=[{"text": "Перенос на 2027 г.", "basis": N}],
        impact={"russia": "Прямых последствий нет", "business": "—", "markets": "Реакции рынков не ожидается"},
        checkpoint={"what": "Указ о дате или официальное подтверждение переноса", "when": "нет даты", "date": None},
        sources=[{"name": "IFES", "url": "https://www.electionguide.org/elections/id/5100/"}],
    ),
    ev(
        id="nicaragua-2026",
        title="Всеобщие выборы в Никарагуа",
        kind="Выборы", cats=["elections", "intl"],
        where="Никарагуа", start=None, window="2026-11-30",
        dateWording="не состоятся",
        dateStatus="cancelled", ideaWording="Expected by November 2026",
        ideaCheck="По IDEA выборы «ожидаются к ноябрю», но конституционная поправка перенесла их на ноябрь 2027 г., а 20 июля 2026 г. сопрезидент Даниэль Ортега объявил об упразднении избирательной системы",
        dateSource={"name": "Next Nicaraguan general election", "url": "https://en.wikipedia.org/wiki/Next_Nicaraguan_general_election"},
        participants="—", agenda=[], scenarios=[],
        impact={"russia": "Никарагуа — союзник России в регионе", "business": "—", "markets": "—"},
        checkpoint={"what": "—", "when": "—", "date": None},
        sources=[{"name": "Next Nicaraguan general election", "url": "https://en.wikipedia.org/wiki/Next_Nicaraguan_general_election"}],
    ),
    ev(
        id="cabo-verde-2026",
        title="Президентские выборы в Кабо-Верде",
        kind="Выборы", cats=["elections", "intl"],
        where="Кабо-Верде", start="2026-11-15T10:00:00+03:00", allDay=True,
        dateStatus="preliminary", ideaWording="scheduled to be held on 15 November 2026",
        dateNote="Дата взята из перечня IDEA; официальный документ избиркома при сверке не найден",
        dateSource={"name": "IDEA", "url": "https://www.idea.int/democracytracker/elections-list"},
        participants="—", agenda=[{"text": "Выборы президента", "basis": A}], scenarios=[],
        impact={"russia": "Прямых последствий нет", "business": "—", "markets": "—"},
        checkpoint={"what": "Итоги", "when": "16 ноября", "date": "2026-11-16"},
        sources=[{"name": "IDEA", "url": "https://www.idea.int/democracytracker/elections-list"}],
    ),
    ev(
        id="rosstat-gdp-q3-2026",
        title="Росстат: первая оценка ВВП за III квартал",
        kind="Публикация данных", cats=["stats", "russia"],
        where="Росстат", start=None, window="2026-11-20",
        dateWording="середина ноября, дата по графику Росстата",
        dateStatus="expected", dateNote="Дату нужно сверить с графиком срочных публикаций на II полугодие",
        dateSource={"name": "Росстат: национальные счета", "url": "https://rosstat.gov.ru/statistics/accounts"},
        participants="—", agenda=[{"text": "Первая оценка ВВП за III квартал 2026 г.", "basis": A}],
        scenarios=[{"text": "Умеренный рост: ЦБ оценивал рост в III квартале как умеренный", "basis": N}],
        impact={"russia": "Покажет, не перешло ли замедление в спад", "business": "—", "markets": "—"},
        checkpoint={"what": "Заседание ЦБ 18 декабря", "when": "18 декабря", "date": "2026-12-18"},
        sources=[{"name": "Росстат", "url": "https://rosstat.gov.ru/statistics/accounts"}],
    ),
    ev(
        id="apec-2026",
        title="Саммит АТЭС",
        kind="Саммит", cats=["intl", "russia"],
        where="Шэньчжэнь, Китай", start="2026-11-18T05:00:00+03:00", end="2026-11-19T14:00:00+03:00",
        timeNote="Саммит деловых кругов АТЭС (CEO Summit) — 17–18 ноября",
        dateStatus="confirmed", dateSource={"name": "Правительство Шэньчжэня", "url": "https://www.sz.gov.cn/en_szgov/news/infocus/APEC2026/News/content/post_12979720.html"},
        participants="Лидеры экономик АТЭС; уровень участия России не объявлен",
        agenda=[{"text": "Приоритеты председательства Китая в АТЭС в 2026 г.", "basis": A}],
        scenarios=[{"text": "Встреча лидеров США и Китая на полях саммита", "basis": N}],
        impact={"russia": "Уровень представительства России — политический сигнал", "business": "Азиатские рынки сбыта", "markets": "Торговые отношения США и Китая"},
        checkpoint={"what": "Декларация лидеров", "when": "19 ноября", "date": "2026-11-19"},
        sources=[{"name": "Shenzhen Government", "url": "https://www.sz.gov.cn/en_szgov/news/infocus/APEC2026/News/content/post_12979720.html"}],
    ),
    ev(
        id="nvda-q3fy27",
        title="Nvidia: отчётность за III квартал 2027 финансового года",
        kind="Отчётность", cats=["business"],
        where="Санта-Клара, США", start="2026-11-25T00:30:00+03:00",
        timeNote="После закрытия торгов в США",
        dateStatus="preliminary", dateNote="Дату называют агрегаторы; сама компания обычно объявляет её примерно за месяц",
        dateSource={"name": "Агрегаторы отчётности", "url": "https://www.investing.com/equities/nvidia-corp-earnings"},
        participants="Руководство Nvidia",
        agenda=[{"text": "Прогноз выручки компании — $108 млрд ±2%", "basis": A}],
        scenarios=[{"text": "Проверка устойчивости ИИ-цикла", "basis": N}],
        impact={"russia": "Прямых последствий нет", "business": "Индикатор ИИ-инвестиций", "markets": "Крупнейшая компания индекса S&P 500"},
        checkpoint={"what": "Подтверждение даты компанией", "when": "конец октября", "date": "2026-10-28"},
        sources=[{"name": "SEC: 8-K за II квартал", "url": "https://www.sec.gov/Archives/edgar/data/0001045810/000104581026000073/q2fy27pr.htm"}],
    ),
    ev(
        id="gambia-president-2026",
        title="Президентские выборы в Гамбии",
        kind="Выборы", cats=["elections", "intl"],
        where="Гамбия", start="2026-12-05T11:00:00+03:00", end="2026-12-05T20:00:00+03:00",
        dateStatus="confirmed", ideaWording="Expected by December 2026",
        ideaCheck="IDEA пишет «ожидаются к декабрю», но избирком назначил дату — 5 декабря; выдвижение с 3 по 14 ноября",
        dateSource={"name": "The Point (Гамбия)", "url": "https://thepoint.gm/africa/gambia/headlines/2026-presidential-election-set-for-dec-5-iec-chairman"},
        participants="Адама Бэрроу идёт на третий срок",
        agenda=[{"text": "Выборы президента", "basis": A}], scenarios=[],
        impact={"russia": "Прямых последствий нет", "business": "—", "markets": "—"},
        checkpoint={"what": "Итоги", "when": "6–7 декабря", "date": "2026-12-07"},
        sources=[{"name": "The Point", "url": "https://thepoint.gm/africa/gambia/headlines/2026-presidential-election-set-for-dec-5-iec-chairman"}],
    ),
    ev(
        id="russia-calling-2026",
        title="Инвестиционный форум ВТБ «Россия зовёт!»",
        kind="Форум", cats=["russia", "business"],
        where="Москва", start=None, window="2026-12-15",
        dateWording="декабрь; в поиске встречаются даты 7–8 декабря, организатор их не подтвердил",
        dateStatus="expected",
        dateNote="Не называть в эфире конкретные числа до анонса ВТБ",
        dateSource={"name": "Поисковые упоминания; нужна сверка с ВТБ", "url": "https://ria.ru/investitsionnyy-forum-vtb-kapital-rossiya-zovt/"},
        participants="ВТБ, инвесторы; по традиции — выступление президента",
        agenda=[{"text": "Программа не опубликована", "basis": A}],
        scenarios=[{"text": "Выступление Владимира Путина с экономическими заявлениями, как в прошлые годы", "basis": N}],
        impact={"russia": "Площадка для экономических заявлений президента в конце года", "business": "Инвестклимат, IPO", "markets": "Акции Мосбиржи"},
        checkpoint={"what": "Анонс даты и программы", "when": "ноябрь", "date": "2026-11-15"},
        sources=[{"name": "РИА Новости: тематическая лента", "url": "https://ria.ru/investitsionnyy-forum-vtb-kapital-rossiya-zovt/"}],
    ),
    ev(
        id="fomc-2026-12",
        title="ФРС: решение по ставке и новые прогнозы",
        kind="Заседание", cats=["cb", "intl"],
        where="Вашингтон", start="2026-12-09T22:00:00+03:00",
        timeNote="Заседание 8–9 декабря. Решение в 14:00 по Вашингтону (зимнее время) = 22:00 мск; «точечный график»",
        dateStatus="confirmed", dateSource={"name": "ФРС", "url": "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm"},
        participants="FOMC", agenda=[{"text": "Ставка; Сводка экономических прогнозов (SEP)", "basis": A}],
        scenarios=[{"text": "Прогнозы на 2027 г. покажут, продолжится ли цикл повышения", "basis": N}],
        impact={"russia": "Через доллар и нефть", "business": "—", "markets": "Главное событие декабря"},
        checkpoint={"what": "Заседание в январе 2027 г.", "when": "январь", "date": None},
        sources=[{"name": "ФРС", "url": "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm"}],
    ),
    ev(
        id="us-cr-deadline-2026-12-11",
        title="США: истекает временное финансирование правительства",
        kind="Срок", cats=["intl", "stats"],
        where="Конгресс США", start="2026-12-11T00:00:00+03:00", allDay=True,
        timeNote="Финансирование действует до конца дня 11 декабря по Вашингтону",
        dateStatus="confirmed", dateSource={"name": "NPR", "url": "https://www.npr.org/2026/09/01/nx-s1-5951536/house-government-funding-vote-midterms"},
        participants="Конгресс, Белый дом",
        agenda=[{"text": "Годовые ассигнования на 2027 финансовый год или новая временная резолюция", "basis": A}],
        scenarios=[
            {"text": "Ещё одна временная резолюция до начала 2027 г.", "basis": N},
            {"text": "Риск частичной остановки правительства, если после выборов расклад в Конгрессе изменится", "basis": N},
        ],
        impact={"russia": "Прямых последствий нет", "business": "—", "markets": "Остановка правительства задерживает публикацию статистики США, как было в 2025 г."},
        checkpoint={"what": "Голосование в Конгрессе", "when": "до 11 декабря", "date": "2026-12-11"},
        sources=[{"name": "NPR", "url": "https://www.npr.org/2026/09/01/nx-s1-5951536/house-government-funding-vote-midterms"},
                 {"name": "CRFB: бюджетные сроки", "url": "https://www.crfb.org/blogs/upcoming-congressional-fiscal-policy-deadlines"}],
    ),
    ev(
        id="haiti-2026",
        title="Гаити: первый тур президентских и парламентских выборов",
        kind="Выборы", cats=["elections", "intl"],
        where="Гаити", start="2026-12-13T14:00:00+03:00", allDay=True,
        dateStatus="preliminary",
        dateNote="Избирательный совет перенёс выборы с 30 августа на 13 декабря и оговорил, что дата зависит от безопасности и финансирования",
        ideaWording="first round … scheduled to be held on 30 August 2026",
        ideaCheck="IDEA всё ещё указывает 30 августа. 27 июля избирательный совет перенёс первый тур на 13 декабря, с оговорками о безопасности",
        dateSource={"name": "Haitian Times / CEP", "url": "https://bitfinance.news/en/haiti-postpones-first-round-of-general-and-legislative-elections-to-december-13/"},
        participants="—", agenda=[{"text": "Первый тур выборов и конституционный референдум", "basis": A}], scenarios=[{"text": "Новый перенос", "basis": N}],
        impact={"russia": "Прямых последствий нет", "business": "—", "markets": "—"},
        checkpoint={"what": "Подтверждение или перенос", "when": "ноябрь", "date": None},
        sources=[{"name": "Bitfinance", "url": "https://bitfinance.news/en/haiti-postpones-first-round-of-general-and-legislative-elections-to-december-13/"}],
    ),
    ev(
        id="g20-2026",
        title="Саммит G20",
        kind="Саммит", cats=["intl", "russia"],
        where="Дорал, Майами (США)", start="2026-12-14T17:00:00+03:00", end="2026-12-15T23:00:00+03:00",
        dateStatus="confirmed", dateSource={"name": "Саммит G20 2026 в Майами", "url": "https://en.wikipedia.org/wiki/2026_G20_Miami_summit"},
        participants="Лидеры G20; участие России не объявлено",
        agenda=[{"text": "Узкая повестка председательства США", "basis": A}],
        scenarios=[{"text": "Уровень участия России и приглашение ЮАР — политические сигналы", "basis": N}],
        impact={"russia": "Формат участия России в G20", "business": "—", "markets": "Слабая реакция рынков"},
        checkpoint={"what": "Декларация лидеров", "when": "15 декабря", "date": "2026-12-15"},
        sources=[{"name": "CFR: председательство США в G20", "url": "https://www.cfr.org/articles/us-g20-presidency-narrow-agenda-2026"}],
    ),
    ev(
        id="ecb-2026-12",
        title="ЕЦБ: решение по ставкам и макропрогнозы",
        kind="Заседание", cats=["cb", "intl"],
        where="Франкфурт", start="2026-12-17T16:15:00+03:00",
        timeNote="16:15 мск, пресс-конференция в 16:45 мск",
        dateStatus="confirmed", dateSource={"name": "ЕЦБ", "url": "https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html"},
        participants="Управляющий совет ЕЦБ", agenda=[{"text": "Ставки; декабрьские макропрогнозы", "basis": A}], scenarios=[],
        impact={"russia": "Курс евро", "business": "—", "markets": "Евро"},
        checkpoint={"what": "Январское заседание", "when": "январь 2027", "date": None},
        sources=[{"name": "ЕЦБ", "url": "https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html"}],
    ),
    ev(
        id="euco-2026-12",
        title="Европейский совет",
        kind="Саммит", cats=["intl", "russia"],
        where="Брюссель", start="2026-12-17T11:00:00+03:00", end="2026-12-18T19:00:00+03:00",
        dateStatus="confirmed", dateSource={"name": "Совет ЕС", "url": "https://www.consilium.europa.eu/en/meetings/european-council/2026/12/17-18/"},
        participants="Лидеры ЕС", agenda=[{"text": "Повестка будет опубликована позже", "basis": A}],
        scenarios=[{"text": "Продление секторальных санкций против России: действующее продлено в июне до конца января 2027 г.", "basis": N}],
        impact={"russia": "Продление санкций, замороженные активы", "business": "—", "markets": "—"},
        checkpoint={"what": "Выводы саммита", "when": "18 декабря", "date": "2026-12-18"},
        sources=[{"name": "Совет ЕС", "url": "https://www.consilium.europa.eu/en/meetings/european-council/2026/12/17-18/"}],
    ),
    ev(
        id="cbr-2026-12-18",
        title="Банк России: решение по ключевой ставке",
        kind="Заседание", cats=["cb", "russia"],
        where="Москва", start="2026-12-18T13:30:00+03:00",
        timeNote="13:30 мск, пресс-конференция в 15:00 мск",
        dateStatus="confirmed", dateSource={"name": "Банк России", "url": "https://cbr.ru/dkp/cal_mp/"},
        participants="Совет директоров Банка России", agenda=[{"text": "Ключевая ставка; последнее заседание года", "basis": A}], scenarios=[],
        impact={"russia": "Задаёт стартовые условия 2027 г.", "business": "Кредитование", "markets": "ОФЗ, рубль"},
        checkpoint={"what": "Календарь заседаний на 2027 г.", "when": "декабрь", "date": None},
        sources=[{"name": "Банк России", "url": "https://cbr.ru/dkp/cal_mp/"}],
    ),
    ev(
        id="putin-year-end-2026",
        title="«Итоги года с Владимиром Путиным»",
        kind="Пресс-конференция", cats=["russia"],
        where="Москва", start=None, window="2026-12-25",
        dateWording="декабрь, дата не объявлена",
        timeNote="В 2025 г. — 19 декабря, 12:00 мск",
        dateStatus="expected", dateSource={"name": "Практика прошлых лет", "url": "https://www.kommersant.ru/theme/232"},
        participants="Президент, журналисты, граждане",
        agenda=[{"text": "Совмещённая прямая линия и большая пресс-конференция", "basis": A}],
        scenarios=[{"text": "Итоги экономики года, налоги 2027 г., внешняя политика", "basis": N}],
        impact={"russia": "Главное медиасобытие года", "business": "Поручения по итогам", "markets": "—"},
        checkpoint={"what": "Анонс Кремля", "when": "ноябрь–декабрь", "date": None},
        sources=[{"name": "Коммерсантъ: тема", "url": "https://www.kommersant.ru/theme/232"}],
    ),
    ev(
        id="south-sudan-2026",
        title="Всеобщие выборы в Южном Судане",
        kind="Выборы", cats=["elections", "intl"],
        where="Южный Судан", start="2026-12-22T09:00:00+03:00", allDay=True,
        dateStatus="confirmed", ideaWording="scheduled to be held on 22 December 2026",
        dateNote="Дата официально назначена Национальной избирательной комиссией, но ООН предупреждает о неготовности. Выборы переносились уже пять раз",
        risk="Высокий риск переноса",
        dateSource={"name": "Совет Безопасности ООН", "url": "https://press.un.org/en/2026/sc16427.doc.htm"},
        participants="—", agenda=[{"text": "Первые в истории страны всеобщие выборы", "basis": A}], scenarios=[{"text": "Шестой перенос", "basis": N}],
        impact={"russia": "Прямых последствий нет", "business": "—", "markets": "—"},
        checkpoint={"what": "Решение о проведении или переносе", "when": "ноябрь–декабрь", "date": None},
        sources=[{"name": "ООН", "url": "https://press.un.org/en/2026/sc16427.doc.htm"}],
    ),

    # ------------------------------------------------------------------ история (уже прошли)
    ev(
        id="opec-plus-2026-09-06",
        title="Встреча стран ОПЕК+ с добровольными ограничениями",
        kind="Заседание", cats=["intl", "russia", "business"],
        where="Онлайн", start="2026-09-06T00:00:00+03:00", allDay=True, phase="closed",
        dateStatus="confirmed", dateSource={"name": "ОПЕК", "url": "https://www.opec.org/pr-detail/613-6-september-2026.html"},
        participants="Семь стран ОПЕК+", agenda=[{"text": "Добыча на октябрь", "basis": A}], scenarios=[],
        impact={"russia": "Нефтяные доходы", "business": "Нефтяники", "markets": "Brent"},
        checkpoint={"what": "Следующая встреча", "when": "4 октября", "date": "2026-10-04"},
        outcome={
            "expected": "Карточка заведена после события, поэтому ожидания до встречи не записывались",
            "decided": "Сохранить на октябрь требуемый уровень добычи сентября",
            "open": ["Решение на ноябрь — 4 октября"],
            "sources": [{"name": "ОПЕК", "url": "https://www.opec.org/pr-detail/613-6-september-2026.html"}],
            "backfilled": True, "filledAt": CHECKED, "filledBy": "claude",
        },
        sources=[{"name": "ОПЕК", "url": "https://www.opec.org/pr-detail/613-6-september-2026.html"}],
    ),
    ev(
        id="ecb-2026-09",
        title="ЕЦБ: решение по ставкам",
        kind="Заседание", cats=["cb", "intl"],
        where="Франкфурт", start="2026-09-10T15:15:00+03:00", phase="closed",
        dateStatus="confirmed", dateSource={"name": "ЕЦБ", "url": "https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html"},
        participants="Управляющий совет", agenda=[{"text": "Ставки, сентябрьские прогнозы", "basis": A}], scenarios=[],
        impact={"russia": "Курс евро", "business": "—", "markets": "Евро"},
        checkpoint={"what": "Следующее заседание", "when": "29 октября", "date": "2026-10-29"},
        outcome={
            "expected": "Карточка заведена после события, поэтому ожидания до заседания не записывались",
            "decided": "Все три ставки повышены на 25 б.п.: депозитная — до 2,50%, основная — до 2,65%, маржинальная — до 2,90% (действует с 16 сентября). Это второе повышение в 2026 г. Причина — энергетическая инфляция на фоне ближневосточного конфликта",
            "open": ["Будет ли третье повышение 29 октября", "Надолго ли инфляция останется выше 2%"],
            "sources": [{"name": "ЕЦБ: ключевые ставки", "url": "https://www.ecb.europa.eu/stats/policy_and_exchange_rates/key_ecb_interest_rates/html/index.en.html"}],
            "backfilled": True, "filledAt": CHECKED, "filledBy": "claude",
        },
        sources=[{"name": "ЕЦБ", "url": "https://www.ecb.europa.eu/stats/policy_and_exchange_rates/key_ecb_interest_rates/html/index.en.html"}],
    ),
    ev(
        id="cbr-2026-09-11",
        title="Банк России: решение по ключевой ставке",
        kind="Заседание", cats=["cb", "russia"],
        where="Москва", start="2026-09-11T13:30:00+03:00", phase="closed",
        dateStatus="confirmed", dateSource={"name": "Банк России", "url": "https://cbr.ru/dkp/cal_mp/"},
        participants="Совет директоров", agenda=[{"text": "Ключевая ставка — 14,00%", "basis": A}], scenarios=[],
        impact={"russia": "Ставка", "business": "Кредит", "markets": "ОФЗ"},
        checkpoint={"what": "Опорное заседание", "when": "23 октября", "date": "2026-10-23"},
        outcome={
            "expected": "Карточка заведена после события. По предварительным материалам СМИ, главный вопрос был, сохранят ли 14%",
            "decided": "Ставка сохранена на уровне 14,00%. Прогноз инфляции на конец 2026 г. — 6–7%. Устойчивый рост цен, по оценке ЦБ, ускорился до 5–6% в пересчёте на год из-за временного сокращения мощностей в отдельных отраслях",
            "open": ["Изменится ли ставка на опорном заседании 23 октября", "Как ЦБ учтёт бюджет-2027 с ростом налогов"],
            "sources": [{"name": "Банк России: пресс-релиз", "url": "https://www.cbr.ru/press/keypr/"}],
            "backfilled": True, "filledAt": CHECKED, "filledBy": "claude",
        },
        sources=[{"name": "Банк России", "url": "https://www.cbr.ru/press/keypr/"}],
    ),
    ev(
        id="fomc-2026-09",
        title="ФРС: решение по ставке",
        kind="Заседание", cats=["cb", "intl"],
        where="Вашингтон", start="2026-09-16T21:00:00+03:00", phase="closed",
        dateStatus="confirmed", dateSource={"name": "ФРС", "url": "https://www.federalreserve.gov/newsevents/pressreleases/monetary20260916a.htm"},
        participants="FOMC", agenda=[{"text": "Ставка, прогнозы", "basis": A}], scenarios=[],
        impact={"russia": "Доллар", "business": "—", "markets": "Мировые рынки"},
        checkpoint={"what": "Следующее заседание", "when": "27–28 октября", "date": "2026-10-28"},
        outcome={
            "expected": "Карточка заведена после события, поэтому ожидания до заседания не записывались",
            "decided": "Ставка повышена на 25 б.п., до 3,75–4,00%, единогласно (12–0). Это первое повышение с 2023 г. Прогнозы членов FOMC на конец года — 4,1–4,4%",
            "open": ["Второе повышение до конца года (рынки закладывают одно)", "Продолжится ли цикл повышения в 2027 г."],
            "sources": [{"name": "ФРС: заявление FOMC", "url": "https://www.federalreserve.gov/newsevents/pressreleases/monetary20260916a.htm"},
                        {"name": "CNBC", "url": "https://www.cnbc.com/2026/09/16/fed-rate-decision-september-2026.html"}],
            "backfilled": True, "filledAt": CHECKED, "filledBy": "claude",
        },
        sources=[{"name": "ФРС", "url": "https://www.federalreserve.gov/newsevents/pressreleases/monetary20260916a.htm"}],
    ),
    ev(
        id="duma-elections-2026",
        title="Выборы в Госдуму IX созыва",
        kind="Выборы", cats=["elections", "russia"],
        where="Россия", start="2026-09-18T08:00:00+03:00", end="2026-09-20T20:00:00+03:00", phase="closed",
        dateStatus="confirmed", dateSource={"name": "ЦИК России", "url": "https://www.vedomosti.ru/politics/news/2026/09/25/1231790-mandatov-v-gosdume"},
        participants="Партии и кандидаты-одномандатники", agenda=[{"text": "450 мандатов", "basis": A}], scenarios=[],
        impact={"russia": "Состав парламента на пять лет", "business": "Налоговое законодательство", "markets": "—"},
        checkpoint={"what": "Первое заседание", "when": "30 сентября", "date": "2026-09-30"},
        outcome={
            "expected": "Карточка заведена после события, поэтому ожидания до выборов не записывались",
            "decided": "ЦИК подвёл итоги 25 сентября: у «Единой России» 349 мандатов, у остальных партий 101. Это наибольший результат одной партии за всю историю Госдумы. Явка — 59,8%",
            "open": ["Распределение комитетов", "Скорость прохождения налогового пакета"],
            "sources": [{"name": "Ведомости", "url": "https://www.vedomosti.ru/politics/news/2026/09/25/1231790-mandatov-v-gosdume"},
                        {"name": "Т—Ж", "url": "https://t-j.ru/news/mandaty-gosduma-2026/"}],
            "backfilled": True, "filledAt": CHECKED, "filledBy": "claude",
        },
        sources=[{"name": "Ведомости", "url": "https://www.vedomosti.ru/politics/news/2026/09/25/1231790-mandatov-v-gosdume"}],
    ),
    ev(
        id="gov-budget-approval-2026-09-24",
        title="Заседание правительства: проект бюджета на 2027–2029 годы",
        kind="Заседание", cats=["russia", "business"],
        where="Москва, Дом правительства", start="2026-09-24T12:00:00+03:00", phase="closed",
        dateStatus="confirmed", dateSource={"name": "Ведомости", "url": "https://www.vedomosti.ru/economics/news/2026/09/24/1231650-pravitelstvo-odobrilo-proekt-byudzheta"},
        participants="Правительство, Минфин", agenda=[{"text": "Проект бюджета", "basis": A}], scenarios=[],
        impact={"russia": "Фискальная политика", "business": "Налоги", "markets": "ОФЗ"},
        checkpoint={"what": "Внесение в Госдуму", "when": "до 1 октября", "date": "2026-10-01"},
        outcome={
            "expected": "Карточка заведена после события, поэтому ожидания до заседания не записывались",
            "decided": "Проект одобрен: доходы 2027 г. — 43,3 трлн руб., расходы — 48,8 трлн руб., дефицит — 2,2% ВВП. В тот же день Минфин внёс в правительство пакет поправок в Налоговый кодекс",
            "open": ["Содержание налогового пакета по статьям", "Изменит ли Дума параметры"],
            "sources": [{"name": "Ведомости", "url": "https://www.vedomosti.ru/economics/articles/2026/09/24/1231407-minfin-vnes"},
                        {"name": "Коммерсантъ", "url": "https://www.kommersant.ru/doc/8974590"}],
            "backfilled": True, "filledAt": CHECKED, "filledBy": "claude",
        },
        sources=[{"name": "Коммерсантъ", "url": "https://www.kommersant.ru/doc/8974590"}],
    ),
]


def main(out_dir):
    os.makedirs(out_dir, exist_ok=True)
    ids = set()
    for e in EVENTS:
        assert e["id"] not in ids, e["id"]
        ids.add(e["id"])
        assert e["dateStatus"] in ("confirmed", "preliminary", "expected", "cancelled"), e["id"]
        if e["dateStatus"] in ("expected", "cancelled"):
            assert e.get("window"), e["id"]
        else:
            assert e.get("start"), e["id"]
        doc = {k: v for k, v in e.items() if k != "id"}
        doc["updatedAt"] = CHECKED
        with open(os.path.join(out_dir, e["id"] + ".json"), "w", encoding="utf-8") as f:
            json.dump(doc, f, ensure_ascii=False, indent=1)
    print(len(EVENTS), "events")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "json"))
