#!/usr/bin/env python3
"""Исходник морских и сухопутных маршрутов для карт сырьевых потоков.

Маршруты собираются из именованных узловых точек (порты, проливы, морские
коридоры), чтобы линии шли по воде. Результат — flows/data/routes.json.
Запуск: python3 flows/fetch/routes_src.py  (после правки маршрутов).
"""
import json
import os

P = {
    # Ближний Восток
    "ras_tanura": (50.2, 26.6), "kharg": (50.3, 29.2), "basra": (48.8, 29.7), "ras_laffan": (51.6, 25.9),
    "hormuz": (56.4, 26.4), "oman_g": (58.8, 24.2), "fujairah": (56.4, 25.2), "arab_sea": (63.0, 19.0),
    "yanbu": (38.1, 24.1), "abqaiq": (49.7, 25.9), "ruwais": (52.7, 24.1),
    # Индия, Азия
    "sikka": (69.8, 22.4), "paradip": (86.7, 20.3), "srilanka": (80.5, 5.2), "andaman": (92.0, 6.0),
    "malacca_n": (97.5, 5.5), "malacca": (100.6, 2.6), "singapore": (103.9, 1.2), "johor_sts": (104.6, 1.9),
    "scs_s": (108.0, 6.0), "scs": (113.0, 13.0), "scs_n": (116.5, 19.5), "guangzhou": (113.6, 22.3),
    "beihai": (109.1, 21.3), "taiwan_s": (119.5, 23.0), "ecs": (123.0, 29.0), "ningbo": (122.0, 29.9),
    "shanghai": (122.3, 31.2), "yellow": (123.0, 35.0), "qingdao": (120.4, 36.0), "dalian": (121.7, 38.9),
    "korea_s": (128.0, 33.5), "busan": (129.1, 35.0), "tsushima": (129.6, 34.2), "japan_s": (134.5, 33.0),
    "tokyo": (139.9, 35.3), "seaofjapan": (133.0, 40.0), "kozmino": (132.9, 42.7), "vostochny": (133.1, 42.8),
    "vanino": (140.3, 49.1), "tatar": (141.0, 47.0), "laperouse": (142.2, 45.6), "sakhalin_s": (143.0, 46.6),
    "bintulu": (113.0, 3.3), "kalimantan": (117.4, -1.0), "makassar": (118.5, -3.0), "java_sea": (112.0, -5.0),
    "lombok": (115.8, -8.8), "darwin": (130.8, -12.0), "timor": (126.0, -11.0),
    "karratha": (116.8, -20.6), "gladstone": (151.3, -23.8), "hay_point": (149.3, -21.3), "newcastle_au": (151.8, -32.9),
    "coral": (154.0, -20.0), "png_e": (153.0, -10.0), "philsea": (130.0, 15.0), "luzon": (121.0, 20.0),
    # Индийский океан, Африка
    "io_c": (75.0, -5.0), "io_s": (60.0, -25.0), "madagascar_s": (45.0, -30.0), "cape": (19.0, -36.0),
    "durban_off": (33.0, -31.0), "richards": (32.1, -28.8), "mozambique": (40.0, -15.0),
    "bab": (43.3, 12.6), "aden": (48.0, 12.5), "redsea": (38.0, 20.5), "suez": (32.6, 29.8), "portsaid": (32.3, 31.4),
    "bonny": (7.2, 4.3), "guinea_g": (3.0, 1.0), "angola_off": (11.0, -9.0), "atl_s": (0.0, -20.0),
    "lagos": (3.4, 6.3), "dakar_off": (-19.0, 14.0), "canary": (-15.0, 28.0), "casablanca": (-7.6, 33.6),
    # Средиземное, Чёрное, Европа
    "med_e": (28.0, 33.5), "crete": (24.0, 34.6), "sicily": (13.0, 37.0), "sardinia": (8.0, 38.5), "algeria_off": (2.0, 37.5),
    "gibraltar": (-5.6, 35.95), "arzew": (-0.3, 35.9), "aliaga": (26.9, 38.8), "mersin": (34.6, 36.7), "ceyhan": (35.8, 36.9),
    "dardanelles": (26.4, 40.1), "marmara": (28.0, 40.7), "bosporus": (29.1, 41.2), "blacksea": (33.5, 43.3),
    "novoross": (37.8, 44.6), "taman": (36.9, 45.1), "trieste": (13.7, 45.6), "genoa": (8.9, 44.4),
    "portugal": (-10.5, 38.5), "finisterre": (-10.0, 43.5), "biscay": (-7.0, 46.5), "brittany": (-6.0, 48.5),
    "channel": (-1.0, 50.2), "dover": (1.6, 51.0), "rotterdam": (4.0, 51.95), "zeebrugge": (3.2, 51.35),
    "north_sea": (4.0, 56.0), "skagerrak": (9.5, 58.0), "kattegat": (11.5, 57.0), "beltsea": (11.0, 55.3),
    "baltic_w": (13.0, 54.8), "baltic": (18.5, 56.5), "gotland": (20.5, 58.2), "gof": (25.0, 59.8),
    "primorsk": (28.6, 60.3), "ustluga": (28.3, 59.7), "norway_w": (4.0, 61.0), "norway_n": (14.0, 69.5),
    "murmansk": (33.0, 69.2), "barents": (40.0, 72.0), "kara_g": (58.0, 70.5), "sabetta": (72.1, 71.3),
    "isle_grain": (0.7, 51.45), "spain_n": (-8.0, 43.5), "huelva": (-6.9, 37.1),
    # Америка
    "corpus": (-97.3, 27.8), "sabine": (-93.9, 29.7), "houston": (-94.8, 29.3), "gulf_mx": (-89.0, 25.5),
    "yucatan": (-86.0, 21.5), "florida": (-81.0, 24.3), "bahamas": (-76.0, 26.5), "atl_w": (-62.0, 32.0),
    "atl_c": (-35.0, 40.0), "atl_ne": (-15.0, 46.0), "caribbean": (-75.0, 15.0), "panama": (-79.7, 9.3),
    "jose": (-64.8, 10.2), "trinidad": (-61.0, 10.8), "brazil_ne": (-34.0, -6.0), "santos": (-46.3, -24.1),
    "brazil_e": (-38.0, -15.0), "atl_sw": (-30.0, -25.0), "hampton": (-76.3, 36.9), "baltimore": (-76.5, 39.2),
    "us_e_off": (-72.0, 36.0), "bolivar": (-71.9, 12.3), "veracruz": (-96.1, 19.2), "chile": (-71.6, -33.0),
    "pacific_sa": (-80.0, -10.0),
    # Суша
    "almetyevsk": (52.3, 54.9), "unecha": (32.7, 52.9), "mozyr": (29.2, 52.0), "brody": (25.2, 50.1),
    "uzhgorod": (22.3, 48.6), "bratislava": (17.2, 48.1), "szazh": (18.9, 47.3), "plock": (19.7, 52.6),
    "schwedt": (14.3, 53.1), "taishet": (98.0, 55.9), "skovorodino": (123.9, 54.0), "mohe": (122.5, 52.9),
    "daqing": (125.0, 46.6), "tengiz": (53.4, 46.1), "atyrau": (51.9, 47.1), "tikhoretsk": (40.1, 45.9),
    "baku": (49.9, 40.4), "tbilisi": (44.8, 41.7), "kirkuk": (44.4, 35.5), "atasu": (71.6, 48.7), "alashankou": (82.6, 45.2),
    "dushanzi": (84.9, 44.3), "edmonton": (-113.5, 53.5), "hardisty": (-111.3, 52.7), "cushing": (-96.8, 36.0),
    "chicago": (-87.6, 41.9), "superior": (-92.1, 46.7), "kuzbass": (86.1, 54.0), "krasnoyarsk": (92.9, 56.0),
    "irkutsk": (104.3, 52.3), "chita": (113.5, 52.0), "zabaikalsk": (117.3, 49.6), "khabarovsk": (135.1, 48.5),
    "gashuun": (105.9, 42.4), "baotou": (110.0, 40.6), "tavan": (105.6, 43.6), "ural": (60.6, 56.8),
    "moscow": (37.6, 55.8), "spb": (30.3, 59.9),
}


def path(*names):
    return [list(P[n]) for n in names]


# Повторяющиеся морские коридоры
GULF_TO_MALACCA = ("hormuz", "oman_g", "arab_sea", "srilanka", "andaman", "malacca_n", "malacca", "singapore")
MALACCA_TO_CHINA_N = ("scs_s", "scs", "scs_n", "taiwan_s", "ecs", "yellow", "qingdao")
SUEZ_FROM_MED = ("crete", "med_e", "portsaid", "suez", "redsea", "bab", "aden", "arab_sea")
BALTIC_OUT = ("gof", "gotland", "baltic", "baltic_w", "beltsea", "kattegat", "skagerrak", "north_sea", "dover", "channel", "brittany", "finisterre", "portugal", "gibraltar", "algeria_off", "sardinia", "sicily")
BLACK_OUT = ("blacksea", "bosporus", "marmara", "dardanelles", "crete")
US_GULF_OUT = ("gulf_mx", "florida", "bahamas", "atl_w", "atl_c", "atl_ne", "brittany", "channel", "dover", "rotterdam")
CAPE_EAST = ("atl_s", "cape", "madagascar_s", "io_s", "io_c", "srilanka", "andaman", "malacca_n", "malacca", "singapore")

R = {
 "crude": [
  dict(id="me_cn", status="disrupted", alert="Ормузский пролив фактически закрыт с 28 февраля 2026 года (короткое открытие с 17 июня до начала июля); маршрут нарушен.", name="Персидский залив → Китай", mode="sea", from_="SA", to="CN",
       route=path("ras_tanura", *GULF_TO_MALACCA, *MALACCA_TO_CHINA_N),
       via=["Ормузский пролив", "Малаккский пролив"],
       flow="Главная нефтяная артерия мира: Саудовская Аравия, Ирак, ОАЭ, Кувейт → Китай.",
       note="Через Ормуз проходит около пятой части мирового потребления нефти; перекрытие пролива — крупнейший риск рынка.",
       pairs=[["SA", "CN"], ["IQ", "CN"], ["AE", "CN"], ["KW", "CN"]]),
  dict(id="me_in", status="disrupted", alert="Ормузский пролив фактически закрыт с 28 февраля 2026 года (короткое открытие с 17 июня до начала июля); маршрут нарушен.", name="Персидский залив → Индия", mode="sea", from_="IQ", to="IN",
       route=path("basra", "kharg", "hormuz", "oman_g", "arab_sea", "sikka"), via=["Ормузский пролив"],
       flow="Ирак, Саудовская Аравия, ОАЭ — традиционные поставщики индийских НПЗ.",
       note="", pairs=[["IQ", "IN"], ["SA", "IN"], ["AE", "IN"]]),
  dict(id="me_jk", status="disrupted", alert="Ормузский пролив фактически закрыт с 28 февраля 2026 года (короткое открытие с 17 июня до начала июля); маршрут нарушен.", name="Персидский залив → Япония и Корея", mode="sea", from_="SA", to="JP",
       route=path("ras_tanura", *GULF_TO_MALACCA, "scs_s", "scs", "scs_n", "luzon", "philsea", "japan_s", "tokyo"),
       via=["Ормузский пролив", "Малаккский пролив"], flow="Япония и Корея получают из Залива большую часть нефти.",
       note="", pairs=[["SA", "JP"], ["AE", "JP"], ["SA", "KR"]]),
  dict(id="me_eu", status="disrupted", alert="Ормузский пролив фактически закрыт с 28 февраля 2026 года (короткое открытие с 17 июня до начала июля); маршрут нарушен.", name="Персидский залив → Европа", mode="sea", from_="SA", to="NL",
       route=path("ras_tanura", "hormuz", "oman_g", "arab_sea", "aden", "bab", "redsea", "suez", "portsaid", "med_e", "crete", "sicily", "sardinia", "algeria_off", "gibraltar", "portugal", "finisterre", "brittany", "channel", "dover", "rotterdam"),
       via=["Ормузский пролив", "Баб-эль-Мандеб", "Суэцкий канал"],
       flow="Часть поставок с 2024 года обходит Красное море вокруг Африки из-за атак хуситов.",
       note="Саудовская Аравия может обходить Ормуз трубой Восток — Запад до Янбу.", pairs=[["SA", "NL"], ["IQ", "IT"], ["SA", "IT"]]),
  dict(id="petroline", name="Восток — Запад (Petroline)", mode="pipe", from_="SA", to="SA",
       route=path("abqaiq", "yanbu"), via=[], flow="С марта 2026 года, после закрытия Ормуза, работает на полную мощность 7 млн барр./сут; отгрузки нефти из Янбу — около 5 млн барр./сут.",
       note="Главный обходной маршрут Залива; вместе с другими обходными трубами заменяет лишь около 9 из ~20 млн барр./сут, ходивших через Ормуз.", pairs=[]),
  dict(id="ru_baltic_in", name="Россия: Балтика → Индия", mode="sea", shadow=True, from_="RU", to="IN",
       route=path("primorsk", *BALTIC_OUT, *SUEZ_FROM_MED, "sikka"),
       via=["Датские проливы", "Гибралтар", "Суэцкий канал"],
       flow="Urals из Приморска и Усть-Луги — главный поток в Индию после эмбарго ЕС.",
       note="По оценкам аналитиков, большая часть российского морского экспорта нефти идёт на танкерах «теневого» флота без западной страховки; ЕС и Великобритания включают такие суда в санкционные списки.",
       pairs=[["RU", "IN"]]),
  dict(id="ru_black", name="Россия: Новороссийск → Индия и Турция", mode="sea", shadow=True, from_="RU", to="IN",
       route=path("novoross", *BLACK_OUT, "med_e", "portsaid", "suez", "redsea", "bab", "aden", "arab_sea", "sikka"),
       via=["Босфор", "Дарданеллы", "Суэцкий канал"], flow="Нефть Urals и казахстанская CPC Blend идут через турецкие проливы.",
       note="Из Новороссийска грузится и казахстанская нефть КТК (не под санкциями).", pairs=[["RU", "TR"]]),
  dict(id="ru_kozmino", name="Россия: Козьмино → Китай", mode="sea", shadow=True, from_="RU", to="CN",
       route=path("kozmino", "seaofjapan", "tsushima", "korea_s", "yellow", "qingdao"), via=["Корейский пролив"],
       flow="Нефть ESPO — короткое плечо до китайских НПЗ Шаньдуна (несколько дней пути).",
       note="Значительную часть перевозят суда «теневого» флота.", pairs=[["RU", "CN"]]),
  dict(id="espo", name="ВСТО (Восточная Сибирь — Тихий океан)", mode="pipe", from_="RU", to="CN",
       route=path("taishet", "irkutsk", "chita", "skovorodino", "khabarovsk", "kozmino"), via=[],
       flow="Около 1,6 млн барр./сут; ответвление Сковородино — Мохэ — Дацин даёт трубный экспорт в Китай.",
       note="Главный восточный маршрут российской нефти.", pairs=[]),
  dict(id="espo_cn", name="Сковородино — Дацин", mode="pipe", from_="RU", to="CN",
       route=path("skovorodino", "mohe", "daqing"), via=[], flow="Трубный экспорт российской нефти в Китай, около 0,6 млн барр./сут.", note="",
       pairs=[]),
  dict(id="druzhba", name="«Дружба» (южная ветка)", mode="pipe", from_="RU", to="HU",
       route=path("almetyevsk", "unecha", "mozyr", "brody", "uzhgorod", "bratislava", "szazh"), via=[],
       flow="Снабжает Венгрию и Словакию; поставки в Германию и Польшу по северной ветке прекращены с 2023 года.",
       note="В 2025 году участки трубопровода и насосные станции подвергались ударам дронов.", pairs=[["RU", "HU"], ["RU", "SK"]]),
  dict(id="druzhba_n", name="«Дружба» (северная ветка)", mode="pipe", status="stopped", from_="RU", to="DE",
       route=path("mozyr", "plock", "schwedt"), via=[],
       flow="Российская нефть в Германию и Польшу не идёт с 2023 года; по трубе Германия получает казахстанскую нефть.",
       note="", pairs=[["KZ", "DE"]]),
  dict(id="cpc", name="КТК (Каспийский трубопроводный консорциум)", mode="pipe", from_="KZ", to="RU",
       route=path("tengiz", "atyrau", "tikhoretsk", "novoross"), via=[],
       flow="Основной экспортный маршрут Казахстана (около 80% экспорта нефти) — через терминал под Новороссийском.",
       note="Казахстан зависит от российской территории; терминал повреждался атаками и штормами.", pairs=[["KZ", "IT"], ["KZ", "NL"]]),
  dict(id="btc", name="Баку — Тбилиси — Джейхан", mode="pipe", from_="AZ", to="TR",
       route=path("baku", "tbilisi", "ceyhan"), via=[], flow="Азербайджанская нефть в Средиземное море в обход России.", note="",
       pairs=[["AZ", "IT"]]),
  dict(id="kirkuk", name="Киркук — Джейхан", mode="pipe", from_="IQ", to="TR",
       route=path("kirkuk", "ceyhan"), via=[], flow="Мощность 1,6 млн барр./сут; экспорт возобновлён в сентябре 2025 года. После закрытия Ормуза — один из немногих выходов иракской нефти, но в 2026 году загружен лишь примерно на 0,2 млн барр./сут.", note="", pairs=[]),
  dict(id="kz_cn", name="Казахстан — Китай", mode="pipe", from_="KZ", to="CN",
       route=path("atasu", "alashankou", "dushanzi"), via=[], flow="Также используется для транзита российской нефти в Китай.", note="",
       pairs=[["KZ", "CN"]]),
  dict(id="ir_cn", status="disrupted", alert="Ормузский пролив фактически закрыт с 28 февраля 2026 года (короткое открытие с 17 июня до начала июля); маршрут нарушен.", name="Иран → Китай", mode="sea", shadow=True, from_="IR", to="CN",
       route=path("kharg", "hormuz", "oman_g", "arab_sea", "srilanka", "andaman", "malacca_n", "malacca", "singapore", "johor_sts", "scs_s", "scs", "scs_n", "taiwan_s", "ecs", "yellow", "qingdao"),
       via=["Ормузский пролив", "Малаккский пролив", "перевалка у Малайзии"],
       flow="Почти весь иранский экспорт уходит независимым НПЗ Шаньдуна; в таможне нефть часто декларируется как малайзийская.",
       note="Поэтому Малайзия в рейтинге выше, чем позволяет её добыча, а Иран не виден в статистике Китая.", pairs=[["MY", "CN"]]),
  dict(id="us_eu", name="США → Европа", mode="sea", from_="US", to="NL",
       route=path("corpus", *US_GULF_OUT), via=["Флоридский пролив"],
       flow="Американская лёгкая нефть заменила российскую в Европе.", note="", pairs=[["US", "NL"], ["US", "GB"], ["US", "DE"]]),
  dict(id="us_asia", name="США → Азия", mode="sea", from_="US", to="KR",
       route=path("corpus", "gulf_mx", "florida", "bahamas", "atl_w", "brazil_ne", "atl_s", "cape", "madagascar_s", "io_s", "io_c", "srilanka", "andaman", "malacca_n", "malacca", "singapore", "scs_s", "scs", "scs_n", "luzon", "korea_s", "busan"),
       via=["мыс Доброй Надежды", "Малаккский пролив"], flow="Крупные танкеры (VLCC) идут вокруг Африки.", note="", pairs=[["US", "KR"], ["US", "IN"], ["US", "CN"]]),
  dict(id="ca_us", name="Канада → США (Enbridge, Keystone)", mode="pipe", from_="CA", to="US",
       route=path("edmonton", "hardisty", "superior", "chicago", "cushing", "houston"), via=[],
       flow="Почти 90% канадской нефти идёт в США по трубопроводам.", note="", pairs=[["CA", "US"]]),
  dict(id="br_cn", name="Бразилия → Китай", mode="sea", from_="BR", to="CN",
       route=path("santos", "atl_sw", "atl_s", *CAPE_EAST[1:], *MALACCA_TO_CHINA_N),
       via=["мыс Доброй Надежды", "Малаккский пролив"], flow="Нефть подсолевых месторождений — растущий поток в Китай.", note="", pairs=[["BR", "CN"]]),
  dict(id="wa_asia", name="Западная Африка → Индия и Европа", mode="sea", from_="NG", to="IN",
       route=path("bonny", "guinea_g", "angola_off", "atl_s", "cape", "madagascar_s", "io_s", "io_c", "arab_sea", "sikka"),
       via=["мыс Доброй Надежды"], flow="Нигерия и Ангола продают нефть в Индию, Европу и Китай.", note="", pairs=[["NG", "IN"], ["NG", "ES"], ["AO", "CN"]]),
 ],
 "products": [
  dict(id="ru_br", name="Россия → Бразилия (дизель)", mode="sea", shadow=True, from_="RU", to="BR",
       route=path("primorsk", "gof", "gotland", "baltic", "baltic_w", "beltsea", "kattegat", "skagerrak", "north_sea", "dover", "channel", "brittany", "finisterre", "portugal", "canary", "dakar_off", "brazil_ne", "brazil_e", "santos"),
       via=["Датские проливы", "Ла-Манш"], flow="Бразилия стала одним из крупнейших покупателей российского дизеля после эмбарго ЕС 2023 года.",
       note="Часть перевозок идёт на судах «теневого» флота; объёмы падают из-за запретов экспорта топлива в России.", pairs=[["RU", "BR"]]),
  dict(id="ru_tr", name="Россия → Турция", mode="sea", shadow=True, from_="RU", to="TR",
       route=path("novoross", "blacksea", "bosporus", "marmara", "dardanelles", "aliaga"), via=["Босфор"],
       flow="Турция — крупнейший покупатель российских нефтепродуктов; часть перепродаётся дальше.", note="", pairs=[["RU", "TR"]]),
  dict(id="ru_af", name="Россия → Северная и Западная Африка", mode="sea", shadow=True, from_="RU", to="MA",
       route=path("ustluga", "gof", "gotland", "baltic", "baltic_w", "beltsea", "kattegat", "skagerrak", "north_sea", "dover", "channel", "brittany", "finisterre", "portugal", "casablanca", "canary", "dakar_off", "lagos"),
       via=["Датские проливы", "Ла-Манш"], flow="Марокко, Тунис, Нигерия, Гана, Того — новые рынки российского топлива.", note="", pairs=[["RU", "MA"], ["RU", "TN"]]),
  dict(id="us_latam", name="США → Латинская Америка", mode="sea", from_="US", to="MX",
       route=path("houston", "gulf_mx", "yucatan", "caribbean", "panama", "pacific_sa", "chile"), via=["Панамский канал"],
       flow="Мексика, Бразилия, Чили — главные покупатели американского дизеля и бензина.", note="", pairs=[["US", "MX"], ["US", "BR"], ["US", "CL"]]),
  dict(id="us_eu_p", name="США → Европа", mode="sea", from_="US", to="NL", route=path("houston", *US_GULF_OUT), via=["Флоридский пролив"],
       flow="Дизель для дефицитного европейского рынка.", note="", pairs=[["US", "NL"], ["US", "FR"]]),
  dict(id="in_eu", name="Индия → Европа", mode="sea", from_="IN", to="NL",
       route=path("sikka", "arab_sea", "io_c", "io_s", "madagascar_s", "cape", "atl_s", "dakar_off", "canary", "portugal", "finisterre", "brittany", "channel", "dover", "rotterdam"),
       via=["мыс Доброй Надежды (в обход Красного моря)"], flow="Дизель и авиакеросин крупнейших экспортных НПЗ Индии.",
       note="С 2026 года ЕС запрещает импорт топлива, произведённого из российской нефти, — это бьёт по индийскому экспорту.", pairs=[["IN", "NL"], ["IN", "FR"]]),
  dict(id="me_eu_p", status="disrupted", alert="Ормузский пролив фактически закрыт с 28 февраля 2026 года (короткое открытие с 17 июня до начала июля); маршрут нарушен.", name="Персидский залив → Европа и Африка", mode="sea", from_="SA", to="NL",
       route=path("ruwais", "hormuz", "oman_g", "arab_sea", "aden", "bab", "redsea", "suez", "portsaid", "med_e", "crete", "sicily", "algeria_off", "gibraltar", "portugal", "finisterre", "brittany", "channel", "dover", "rotterdam"),
       via=["Ормузский пролив", "Суэцкий канал"], flow="Новые НПЗ Саудовской Аравии, ОАЭ и Кувейта продают дизель в Европу и Восточную Африку.", note="",
       pairs=[["SA", "NL"], ["AE", "NL"], ["KW", "NL"]]),
  dict(id="nl_wa", name="Роттердам → Западная Африка", mode="sea", from_="NL", to="NG",
       route=path("rotterdam", "dover", "channel", "brittany", "finisterre", "portugal", "canary", "dakar_off", "lagos"),
       via=["Ла-Манш"], flow="Европейский хаб перепродаёт и смешивает топливо для Африки.", note="Новый НПЗ Данготе в Нигерии сокращает этот поток.",
       pairs=[["NL", "NG"], ["BE", "NG"]]),
  dict(id="sg_au", name="Сингапур, Корея → Австралия", mode="sea", from_="SG", to="AU",
       route=path("singapore", "java_sea", "lombok", "timor", "darwin", "coral", "newcastle_au"), via=["Ломбокский пролив"],
       flow="Австралия импортирует почти всё топливо из Азии.", note="", pairs=[["SG", "AU"], ["KR", "AU"]]),
  dict(id="kr_cn_as", name="Корея и Китай → Юго-Восточная Азия", mode="sea", from_="KR", to="SG",
       route=path("busan", "korea_s", "ecs", "taiwan_s", "scs_n", "scs", "scs_s", "singapore"), via=["Тайваньский пролив"],
       flow="Экспортные НПЗ Северо-Восточной Азии снабжают регион.", note="", pairs=[["KR", "SG"], ["CN", "SG"]]),
 ],
 "lng": [
  dict(id="us_eu_l", name="США → Европа", mode="sea", from_="US", to="NL",
       route=path("sabine", *US_GULF_OUT), via=["Флоридский пролив"],
       flow="Больше половины американского СПГ идёт в Европу; США — главный поставщик СПГ в ЕС.", note="",
       pairs=[["US", "NL"], ["US", "FR"], ["US", "GB"], ["US", "ES"]]),
  dict(id="us_asia_l", name="США → Азия", mode="sea", from_="US", to="JP",
       route=path("sabine", "gulf_mx", "florida", "bahamas", "atl_w", "brazil_ne", "atl_s", "cape", "madagascar_s", "io_s", "io_c", "srilanka", "andaman", "malacca_n", "malacca", "singapore", "scs_s", "scs", "scs_n", "luzon", "philsea", "japan_s", "tokyo"),
       via=["мыс Доброй Надежды", "Малаккский пролив"],
       flow="Газовозы идут в Азию вокруг Африки или через Панамский канал, когда тот не ограничен засухой.", note="Маршрут на карте схематичный.",
       pairs=[["US", "JP"], ["US", "KR"], ["US", "CN"]]),
  dict(id="qa_asia", status="disrupted", alert="Ормузский пролив фактически закрыт с 28 февраля 2026 года (короткое открытие с 17 июня до начала июля); маршрут нарушен.", name="Катар → Азия", mode="sea", from_="QA", to="CN",
       route=path("ras_laffan", *GULF_TO_MALACCA, *MALACCA_TO_CHINA_N[:5], "shanghai"), via=["Ормузский пролив", "Малаккский пролив"],
       flow="Китай, Индия, Корея, Япония — основные рынки катарского СПГ.", note="Весь катарский СПГ проходит через Ормуз.",
       pairs=[["QA", "CN"], ["QA", "IN"], ["QA", "KR"]]),
  dict(id="qa_eu", status="disrupted", alert="Ормузский пролив фактически закрыт с 28 февраля 2026 года (короткое открытие с 17 июня до начала июля); маршрут нарушен.", name="Катар → Европа", mode="sea", from_="QA", to="IT",
       route=path("ras_laffan", "hormuz", "oman_g", "arab_sea", "aden", "bab", "redsea", "suez", "portsaid", "med_e", "sicily", "genoa"),
       via=["Ормузский пролив", "Баб-эль-Мандеб", "Суэцкий канал"],
       flow="С 2024 года катарские газовозы в основном обходят Красное море вокруг Африки.", note="", pairs=[["QA", "IT"], ["QA", "BE"], ["QA", "GB"]]),
  dict(id="au_asia", name="Австралия → Япония, Китай, Корея", mode="sea", from_="AU", to="JP",
       route=path("gladstone", "coral", "png_e", "philsea", "japan_s", "tokyo"), via=[],
       flow="Заводы Квинсленда и Западной Австралии работают на долгосрочные контракты с Азией.", note="",
       pairs=[["AU", "JP"], ["AU", "CN"], ["AU", "KR"]]),
  dict(id="au_w", name="Западная Австралия → Китай", mode="sea", from_="AU", to="CN",
       route=path("karratha", "timor", "makassar", "scs_s", "scs", "scs_n", "guangzhou"), via=["Макассарский пролив"],
       flow="", note="", pairs=[]),
  dict(id="ru_yamal_eu", name="Ямал СПГ → Европа", mode="sea", from_="RU", to="BE",
       route=path("sabetta", "kara_g", "barents", "murmansk", "norway_n", "norway_w", "north_sea", "zeebrugge"),
       via=["Северный морской путь (западная часть)"],
       flow="Значительная часть Ямал СПГ всё ещё идёт в ЕС (Бельгия, Франция, Испания).",
       note="ЕС запрещает российский СПГ: по краткосрочным контрактам с 25 апреля 2026 года, по долгосрочным — с 1 января 2027 года.",
       pairs=[["RU", "BE"], ["RU", "FR"], ["RU", "ES"]]),
  dict(id="ru_arctic2", name="Арктик СПГ 2 → Китай", mode="sea", shadow=True, from_="RU", to="CN",
       route=path("sabetta", "kara_g", "barents", "murmansk", "norway_n", "norway_w", "north_sea", "dover", "channel", "brittany", "finisterre", "portugal", "gibraltar", "algeria_off", "sicily", "crete", "med_e", "portsaid", "suez", "redsea", "bab", "aden", "arab_sea", "srilanka", "andaman", "malacca_n", "malacca", "singapore", "scs_s", "scs", "beihai"),
       via=["Суэцкий канал", "Малаккский пролив"],
       flow="Проект под санкциями США; с 2025 года грузы принимает китайский терминал Бэйхай. Летом часть рейсов идёт Северным морским путём.",
       note="Перевозки — на газовозах «теневого» флота; маршрут на карте схематичный.", pairs=[]),
  dict(id="ru_sakh", name="Сахалин-2 → Япония и Китай", mode="sea", from_="RU", to="JP",
       route=path("sakhalin_s", "laperouse", "seaofjapan", "tsushima", "japan_s", "tokyo"), via=["пролив Лаперуза"],
       flow="Япония сохранила закупки СПГ с Сахалина-2 ради энергобезопасности.", note="", pairs=[["RU", "JP"], ["RU", "CN"]]),
  dict(id="my_asia", name="Малайзия (Бинтулу) → Северо-Восточная Азия", mode="sea", from_="MY", to="JP",
       route=path("bintulu", "scs", "scs_n", "luzon", "philsea", "japan_s", "tokyo"), via=[], flow="", note="", pairs=[["MY", "JP"], ["MY", "CN"]]),
  dict(id="dz_eu_l", name="Алжир → Южная Европа", mode="sea", from_="DZ", to="TR",
       route=path("arzew", "algeria_off", "sicily", "crete", "dardanelles", "marmara"), via=["Дарданеллы"],
       flow="Алжирский СПГ дополняет трубные поставки в Италию и Испанию, идёт также в Турцию.", note="", pairs=[["DZ", "TR"], ["DZ", "FR"], ["DZ", "IT"]]),
  dict(id="ng_l", name="Нигерия → Европа и Азия", mode="sea", from_="NG", to="ES",
       route=path("bonny", "guinea_g", "dakar_off", "canary", "huelva"), via=[], flow="", note="", pairs=[["NG", "ES"], ["NG", "FR"]]),
 ],
 "coal": [
  dict(id="au_jk", name="Австралия → Япония, Корея, Тайвань", mode="sea", from_="AU", to="JP",
       route=path("newcastle_au", "coral", "png_e", "philsea", "japan_s", "tokyo"), via=[],
       flow="Энергетический уголь из Ньюкасла — для электростанций Северо-Восточной Азии.", note="", pairs=[["AU", "JP"], ["AU", "KR"]]),
  dict(id="au_in", name="Австралия → Индия (коксующийся)", mode="sea", from_="AU", to="IN",
       route=path("hay_point", "coral", "png_e", "timor", "lombok", "io_c", "srilanka", "paradip"), via=["Ломбокский пролив"],
       flow="Металлургический уголь Квинсленда — для индийской металлургии.", note="", pairs=[["AU", "IN"]]),
  dict(id="au_cn", name="Австралия → Китай", mode="sea", from_="AU", to="CN",
       route=path("newcastle_au", "coral", "png_e", "philsea", "luzon", "taiwan_s", "ecs", "ningbo"), via=[],
       flow="Поставки восстановились после снятия неофициального китайского запрета в 2023 году.", note="", pairs=[["AU", "CN"]]),
  dict(id="id_cn", name="Индонезия → Китай", mode="sea", from_="ID", to="CN",
       route=path("kalimantan", "makassar", "scs", "scs_n", "guangzhou"), via=[],
       flow="Короткое плечо, дешёвый низкокалорийный уголь — главный поток энергетического угля в мире.", note="Часть индонезийского угля декларируется как бурый (HS 2702) и в сумму по каменному углю (HS 2701) не попадает, поэтому таможенная стоимость занижена.", pairs=[["ID", "CN"]]),
  dict(id="id_in", name="Индонезия → Индия", mode="sea", from_="ID", to="IN",
       route=path("kalimantan", "java_sea", "singapore", "malacca", "malacca_n", "andaman", "paradip"), via=["Малаккский пролив"],
       flow="", note="", pairs=[["ID", "IN"]]),
  dict(id="ru_east", name="Россия: Кузбасс → порты Дальнего Востока → Азия", mode="rail", from_="RU", to="CN",
       route=path("kuzbass", "krasnoyarsk", "irkutsk", "chita", "skovorodino", "khabarovsk", "vanino"), via=["Транссиб и БАМ"],
       flow="Главный экспортный путь российского угля; упирается в пропускную способность железных дорог на восток.", note="", pairs=[]),
  dict(id="ru_east_sea", name="Россия: Восточный, Ванино → Китай и Корея", mode="sea", from_="RU", to="CN",
       route=path("vostochny", "seaofjapan", "tsushima", "korea_s", "yellow", "qingdao"), via=["Корейский пролив"],
       flow="Япония отказалась от российского угля в 2022 году; основные покупатели — Китай и Корея.", note="", pairs=[["RU", "CN"], ["RU", "KR"]]),
  dict(id="ru_rail_cn", name="Россия → Китай по железной дороге", mode="rail", from_="RU", to="CN",
       route=path("chita", "zabaikalsk", "daqing"), via=["Забайкальск"], flow="Сухопутный экспорт через погранпереходы.", note="", pairs=[]),
  dict(id="ru_west", name="Россия: балтийские и черноморские порты → Индия и Турция", mode="sea", from_="RU", to="IN",
       route=path("taman", "blacksea", "bosporus", "marmara", "dardanelles", "crete", "med_e", "portsaid", "suez", "redsea", "bab", "aden", "arab_sea", "sikka"),
       via=["Босфор", "Суэцкий канал"], flow="После эмбарго ЕС с августа 2022 года западные порты отправляют уголь в Турцию, Индию и Африку.", note="",
       pairs=[["RU", "TR"], ["RU", "IN"]]),
  dict(id="mn_cn", name="Монголия → Китай", mode="rail", from_="MN", to="CN",
       route=path("tavan", "gashuun", "baotou"), via=[], flow="Коксующийся уголь Таван-Толгоя; новые железные дороги к границе.", note="Почти весь экспорт Монголии — в Китай.",
       pairs=[["MN", "CN"]]),
  dict(id="us_coal", name="США → Индия и Европа", mode="sea", from_="US", to="IN",
       route=path("hampton", "us_e_off", "atl_c", "canary", "dakar_off", "atl_s", "cape", "madagascar_s", "io_s", "io_c", "arab_sea", "sikka"),
       via=["мыс Доброй Надежды"], flow="Металлургический уголь Аппалачей.", note="Китай ввёл пошлину на американский уголь в 2025 году.", pairs=[["US", "IN"], ["US", "NL"]]),
  dict(id="za_in", name="ЮАР → Индия и Пакистан", mode="sea", from_="ZA", to="IN",
       route=path("richards", "durban_off", "mozambique", "io_c", "arab_sea", "sikka"), via=[], flow="Экспорт через терминал Ричардс-Бей.", note="Ограничен перебоями госжелдороги Transnet.",
       pairs=[["ZA", "IN"], ["ZA", "PK"]]),
  dict(id="co_eu", name="Колумбия → Европа и Турция", mode="sea", from_="CO", to="TR",
       route=path("bolivar", "caribbean", "atl_w", "atl_c", "portugal", "gibraltar", "algeria_off", "sicily", "crete", "dardanelles", "marmara"),
       via=["Гибралтар"], flow="", note="", pairs=[["CO", "TR"], ["CO", "NL"]]),
 ],
}

out = {"_readme": "Маршруты перевозки сырья для карт в карточках рынков. Генерируется fetch/routes_src.py — правьте там. mode: sea | pipe | rail; shadow: перевозки «теневым» флотом; status: operating | stopped; pairs — пары стран для стоимости торговли по UN Comtrade (код HS рынка).",
       "_reviewed": "2026-10-02", "markets": {}}
for m, lst in R.items():
    rows = []
    for r in lst:
        r = dict(r)
        r["from"] = r.pop("from_")
        r.setdefault("status", "operating")
        r.setdefault("alert", "")
        r.setdefault("shadow", False)
        rows.append(r)
    out["markets"][m] = rows
dst = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "routes.json")
with open(dst, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=1)
print("routes.json:", {k: len(v) for k, v in out["markets"].items()})
